-- ============================================================
-- Copia todos os objetivos de PSICOPEDAGOGIA (ID_ESP=3)
-- para FISIOTERAPIA (ID_ESP=1) e TERAPIA OCUPACIONAL (ID_ESP=4)
-- (apenas os que ainda não existem em cada especialidade)
-- ============================================================

-- Para FISIOTERAPIA
INSERT INTO FAV_TB_OBJETIVO_CERIV (ID_OBJETIVO, ID_ESPECIALIDADE, DS_OBJETIVO)
SELECT
    (SELECT MAX(ID_OBJETIVO) FROM FAV_TB_OBJETIVO_CERIV) + ROWNUM,
    1,
    DS_OBJETIVO
FROM FAV_TB_OBJETIVO_CERIV
WHERE ID_ESPECIALIDADE = 3
  AND DS_OBJETIVO NOT IN (
      SELECT DS_OBJETIVO FROM FAV_TB_OBJETIVO_CERIV WHERE ID_ESPECIALIDADE = 1
  );

-- Para TERAPIA OCUPACIONAL
INSERT INTO FAV_TB_OBJETIVO_CERIV (ID_OBJETIVO, ID_ESPECIALIDADE, DS_OBJETIVO)
SELECT
    (SELECT MAX(ID_OBJETIVO) FROM FAV_TB_OBJETIVO_CERIV) + ROWNUM,
    4,
    DS_OBJETIVO
FROM FAV_TB_OBJETIVO_CERIV
WHERE ID_ESPECIALIDADE = 3
  AND DS_OBJETIVO NOT IN (
      SELECT DS_OBJETIVO FROM FAV_TB_OBJETIVO_CERIV WHERE ID_ESPECIALIDADE = 4
  );

COMMIT;
