-- =========================================================================
-- FIX: Adiciona colunas NR (Sem Resposta) que faltam na tabela
-- Execute este script no banco para corrigir o erro de coluna não encontrada
-- =========================================================================

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE FAV_TB_SILA_RESULTADOS_AUDIO ADD OD_VA_250_NR  NUMBER(1) DEFAULT 0';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -1430 THEN RAISE; END IF; -- Ignora se coluna já existe
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE FAV_TB_SILA_RESULTADOS_AUDIO ADD OD_VA_500_NR  NUMBER(1) DEFAULT 0';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE FAV_TB_SILA_RESULTADOS_AUDIO ADD OD_VA_1000_NR NUMBER(1) DEFAULT 0';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE FAV_TB_SILA_RESULTADOS_AUDIO ADD OD_VA_2000_NR NUMBER(1) DEFAULT 0';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE FAV_TB_SILA_RESULTADOS_AUDIO ADD OD_VA_3000_NR NUMBER(1) DEFAULT 0';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE FAV_TB_SILA_RESULTADOS_AUDIO ADD OD_VA_4000_NR NUMBER(1) DEFAULT 0';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE FAV_TB_SILA_RESULTADOS_AUDIO ADD OD_VA_6000_NR NUMBER(1) DEFAULT 0';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE FAV_TB_SILA_RESULTADOS_AUDIO ADD OD_VA_8000_NR NUMBER(1) DEFAULT 0';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE FAV_TB_SILA_RESULTADOS_AUDIO ADD OD_VO_500_NR  NUMBER(1) DEFAULT 0';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE FAV_TB_SILA_RESULTADOS_AUDIO ADD OD_VO_1000_NR NUMBER(1) DEFAULT 0';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE FAV_TB_SILA_RESULTADOS_AUDIO ADD OD_VO_2000_NR NUMBER(1) DEFAULT 0';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE FAV_TB_SILA_RESULTADOS_AUDIO ADD OD_VO_4000_NR NUMBER(1) DEFAULT 0';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE FAV_TB_SILA_RESULTADOS_AUDIO ADD OE_VA_250_NR  NUMBER(1) DEFAULT 0';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE FAV_TB_SILA_RESULTADOS_AUDIO ADD OE_VA_500_NR  NUMBER(1) DEFAULT 0';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE FAV_TB_SILA_RESULTADOS_AUDIO ADD OE_VA_1000_NR NUMBER(1) DEFAULT 0';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE FAV_TB_SILA_RESULTADOS_AUDIO ADD OE_VA_2000_NR NUMBER(1) DEFAULT 0';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE FAV_TB_SILA_RESULTADOS_AUDIO ADD OE_VA_3000_NR NUMBER(1) DEFAULT 0';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE FAV_TB_SILA_RESULTADOS_AUDIO ADD OE_VA_4000_NR NUMBER(1) DEFAULT 0';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE FAV_TB_SILA_RESULTADOS_AUDIO ADD OE_VA_6000_NR NUMBER(1) DEFAULT 0';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE FAV_TB_SILA_RESULTADOS_AUDIO ADD OE_VA_8000_NR NUMBER(1) DEFAULT 0';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE FAV_TB_SILA_RESULTADOS_AUDIO ADD OE_VO_500_NR  NUMBER(1) DEFAULT 0';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE FAV_TB_SILA_RESULTADOS_AUDIO ADD OE_VO_1000_NR NUMBER(1) DEFAULT 0';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE FAV_TB_SILA_RESULTADOS_AUDIO ADD OE_VO_2000_NR NUMBER(1) DEFAULT 0';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE FAV_TB_SILA_RESULTADOS_AUDIO ADD OE_VO_4000_NR NUMBER(1) DEFAULT 0';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

COMMIT;
