-- Inserir diagnósticos visuais (OFTALMOLOGIA) com id_especialidade = 14
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (14, 'NÃO SE APLICA');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (14, 'ALBINISMO OCULAR');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (14, 'ALTA MIOPIA');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (14, 'AMBLIOPIA');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (14, 'ANIRIDIA');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (14, 'ANOFTALMIA');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (14, 'ATROFIA GEOGRÁFICA DA RETINA');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (14, 'BAIXA VISÃO');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (14, 'CATARATA CONGÊNITA');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (14, 'CATARATA INFANTIL');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (14, 'CERATOCONE');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (14, 'DEGENERAÇÃO MACULAR');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (14, 'DESCOLAMENTO DE RETINA');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (14, 'DISPLASIA SEPTO-ÓPTICA');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (14, 'GLAUCOMA');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (14, 'HEMIANOPSIA');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (14, 'LEUCOMALÁCIA PERIVENTRICULAR');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (14, 'NISTAGMO');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (14, 'RETINOPATIA DA PREMATURIDADE');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (14, 'RETINOSE PIGMENTAR');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (14, 'OUTROS');

COMMIT;
