-- Inserir especialidade OFTALMOLOGIA
INSERT INTO TB_FAV_ESPECIALIDADE_CERIV (ID_ESPECIALIDADE, DS_ESPECIALIDADE) VALUES (14, 'OFTALMOLOGIA');

-- Inserir diagnósticos visuais (OFTALMOLOGIA) com id_especialidade = 14
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'NÃO SE APLICA', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'ALBINISMO OCULAR', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'ALTA MIOPIA', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'AMBLIOPIA', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'ANIRIDIA', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'ANOFTALMIA', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'ATROFIA GEOGRÁFICA DA RETINA', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'BAIXA VISÃO', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'CATARATA CONGÊNITA', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'CATARATA INFANTIL', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'CERATOCONE', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'DEGENERAÇÃO MACULAR', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'DESCOLAMENTO DE RETINA', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'DISPLASIA SEPTO-ÓPTICA', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'GLAUCOMA', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'HEMIANOPSIA', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'LEUCOMALÁCIA PERIVENTRICULAR', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'NISTAGMO', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'RETINOPATIA DA PREMATURIDADE', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'RETINOSE PIGMENTAR', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'OUTROS', 'S');

COMMIT;
