-- ============================================================================
-- SCRIPT PARA ADICIONAR DIAGNÓSTICOS DA SEÇÃO 01 DO PTS (APENAS OS FALTANTES)
-- ============================================================================
-- 
-- TABELA: TB_FAV_DIAGNOSTICO_CERIV
-- COLUNA id_especialidade = 1 (PRINCIPAL)
-- 
-- Este script insere os diagnósticos que constavam no Print 01 (lista necessária)
-- mas estavam ausentes ou divergentes no Print 02 (tabela do banco de dados).
-- ============================================================================

INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 1, 'EPLEPSIA DE DIFICIL CONTROLE ASSOCIADO A ATRASO DO DE', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 1, 'MIELOMENINGINCELE', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 1, 'SINDROME CONGENITA DO ZIKA VIRUS( SCZV)', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 1, 'TRANSTORNO DO ESPECTRO AUTISTA ( TEA)', 'S');

COMMIT;
