-- ============================================================================
-- SCRIPT PARA ADICIONAR DIAGNÓSTICOS DE OFTALMOLOGIA (APENAS OS FALTANTES)
-- ============================================================================
-- 
-- TABELA: TB_FAV_DIAGNOSTICO_CERIV
-- COLUNA id_especialidade = 14 (OFTALMOLOGIA)
-- 
-- Este script insere na tabela TB_FAV_DIAGNOSTICO_CERIV apenas os diagnósticos
-- de oftalmologia que constavam na lista desejada mas ainda não existiam no banco.
--
-- Total: 37 diagnósticos adicionados
-- ============================================================================

-- 1. INSERTAR DIAGNÓSTICOS DE OFTALMOLOGIA (id_especialidade = 14)

INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'CATARATA', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'CATARATA TRAUMÁTICA', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'CEGUEIRA', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'CEGUEIRA CORTICAL', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'CICATRIZ DE MÁCULA', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'COLOBOMA DO NERVO ÓPTICO/RETINA', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'CORIORRETINITE', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'DEGENERAÇÃO MACULAR RELACIONADA A IDADE (DMRI)', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'DISTROFIA DE RETINA', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'DOENÇA DE AICARDI', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'DOENÇA DE COATS', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'DOENÇA DE LEBER', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'DOENÇA DE LYME', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'DOENÇA DE PETERS', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'DOENÇA DE STARGART', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'ESTRABISMO', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'GLAUCOMA CONGÊNITO', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'GLAUCOMA NEUROVASCULAR', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'GLIOMA DO NERVO ÓPTICO', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'HIPERMETROPIA ALTA', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'LESÃO NA CÓRNEA', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'MAL FORMAÇÃO CONGÊNITA MÚLTIPLA (MFCM)', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'MICROCEFALIA', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'MICROCEFALIA PELO VÍRUS DA ZIKA', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'MIOPIA DEGENERATIVA', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'NEURITE ÓPTICA', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'OPACIDADE CORNEANA', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'RETINOBLASTOMA', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'RETINOPATIA DA PREMATURIDADE - ROP', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'RETINOPATIA DIABÉTICA', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'SEQUELA DE TUMOR CEREBRAL', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'SÍNDROME DE PETERS', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'SÍNDROME DE USHER', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'SUBLUXAÇÃO DO CRISTALINO', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'TRAUMA OCULAR', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'TRAUMA POR ARMA DE FOGO (PAF)', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 14, 'UVEÍTE', 'S');

COMMIT;

