-- ============================================================================
-- SCRIPT DE CRIAÇÃO DE TABELAS PARA MÓDULO DE PSICOLOGIA
-- ============================================================================
-- Executar como admin no Oracle para criar as estruturas necessárias

-- ============================================================================
-- 1. TABELA PRINCIPAL: FAV_TB_PSICOLOGIA_DOCUMENTOS
-- ============================================================================
CREATE TABLE FAV_TB_PSICOLOGIA_DOCUMENTOS (
    ID_PSICOLOGIA_DOC    NUMBER(10) PRIMARY KEY,
    CD_PACIENTE          VARCHAR2(20) NOT NULL,
    ID_USUARIO           NUMBER(10) NOT NULL,
    DS_TIPO_DOC          VARCHAR2(30) NOT NULL,  -- ANAMNESE, EVOLUCAO, AVALIACAO, etc
    DT_CRIACAO           TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    DT_ATUALIZACAO       TIMESTAMP(6) WITH TIME ZONE,
    ID_USUARIO_ULTIMA_EDICAO NUMBER(10),
    FL_ATIVO             NUMBER(1) DEFAULT 1 NOT NULL,
    DS_OBSERVACOES       VARCHAR2(4000),
    
    CONSTRAINT FK_PSICOLOGIA_DOCS_USUARIO 
        FOREIGN KEY (ID_USUARIO) REFERENCES FAV_TB_SILA_USUARIOS(ID_USUARIO),
    CONSTRAINT FK_PSICOLOGIA_DOCS_USUARIO_EDICAO 
        FOREIGN KEY (ID_USUARIO_ULTIMA_EDICAO) REFERENCES FAV_TB_SILA_USUARIOS(ID_USUARIO),
    CONSTRAINT CHK_PSICOLOGIA_TIPO_DOC 
        CHECK (DS_TIPO_DOC IN ('ANAMNESE', 'EVOLUCAO', 'AVALIACAO')),
    CONSTRAINT CHK_PSICOLOGIA_ATIVO 
        CHECK (FL_ATIVO IN (0, 1))
);

CREATE INDEX IDX_PSICOLOGIA_DOCS_PACIENTE ON FAV_TB_PSICOLOGIA_DOCUMENTOS(CD_PACIENTE);
CREATE INDEX IDX_PSICOLOGIA_DOCS_USUARIO ON FAV_TB_PSICOLOGIA_DOCUMENTOS(ID_USUARIO);
CREATE INDEX IDX_PSICOLOGIA_DOCS_TIPO ON FAV_TB_PSICOLOGIA_DOCUMENTOS(DS_TIPO_DOC);
CREATE INDEX IDX_PSICOLOGIA_DOCS_DATA ON FAV_TB_PSICOLOGIA_DOCUMENTOS(DT_CRIACAO);

-- Sequência para ID
CREATE SEQUENCE SEQ_PSICOLOGIA_DOC INCREMENT BY 1 START WITH 1;

-- ============================================================================
-- 2. TABELA: FAV_TB_PSICOLOGIA_ANAMNESE
-- ============================================================================
CREATE TABLE FAV_TB_PSICOLOGIA_ANAMNESE (
    ID_ANAMNESE              NUMBER(10) PRIMARY KEY,
    ID_PSICOLOGIA_DOC        NUMBER(10) NOT NULL UNIQUE,
    DS_HISTORIA_FAMILIAR     VARCHAR2(4000),
    DS_HISTORIA_PESSOAL      VARCHAR2(4000),
    DS_ESCOLARIDADE          VARCHAR2(500),
    DS_SOCIOECONOMICO        VARCHAR2(500),
    DS_QUEIXA_PRINCIPAL      VARCHAR2(4000),
    DS_HIPOTESE_INICIAL      VARCHAR2(4000),
    DT_CRIACAO               TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    DT_ATUALIZACAO           TIMESTAMP(6) WITH TIME ZONE,
    
    CONSTRAINT FK_ANAMNESE_DOCS 
        FOREIGN KEY (ID_PSICOLOGIA_DOC) REFERENCES FAV_TB_PSICOLOGIA_DOCUMENTOS(ID_PSICOLOGIA_DOC) ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_PSICOLOGIA_ANAMNESE INCREMENT BY 1 START WITH 1;

-- ============================================================================
-- 3. TABELA: FAV_TB_PSICOLOGIA_EVOLUCAO
-- ============================================================================
CREATE TABLE FAV_TB_PSICOLOGIA_EVOLUCAO (
    ID_EVOLUCAO              NUMBER(10) PRIMARY KEY,
    ID_PSICOLOGIA_DOC        NUMBER(10) NOT NULL,
    NR_ATENDIMENTO           VARCHAR2(20),
    DS_DATA_ATENDIMENTO      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    DS_OBSERVACOES           VARCHAR2(4000),
    DS_OBJETIVOS_SESSAO      VARCHAR2(2000),
    DS_INTERVENCOES          VARCHAR2(4000),
    DS_PROXIMOS_PASSOS       VARCHAR2(2000),
    ID_USUARIO_CRIOU         NUMBER(10) NOT NULL,
    DT_CRIACAO               TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    DT_ATUALIZACAO           TIMESTAMP(6) WITH TIME ZONE,
    
    CONSTRAINT FK_EVOLUCAO_DOCS 
        FOREIGN KEY (ID_PSICOLOGIA_DOC) REFERENCES FAV_TB_PSICOLOGIA_DOCUMENTOS(ID_PSICOLOGIA_DOC) ON DELETE CASCADE,
    CONSTRAINT FK_EVOLUCAO_USUARIO 
        FOREIGN KEY (ID_USUARIO_CRIOU) REFERENCES FAV_TB_SILA_USUARIOS(ID_USUARIO)
);

CREATE INDEX IDX_EVOLUCAO_DOCS ON FAV_TB_PSICOLOGIA_EVOLUCAO(ID_PSICOLOGIA_DOC);
CREATE INDEX IDX_EVOLUCAO_DATA ON FAV_TB_PSICOLOGIA_EVOLUCAO(DS_DATA_ATENDIMENTO);
CREATE SEQUENCE SEQ_PSICOLOGIA_EVOLUCAO INCREMENT BY 1 START WITH 1;

-- ============================================================================
-- 4. TABELA: FAV_TB_PSICOLOGIA_AVALIACAO
-- ============================================================================
CREATE TABLE FAV_TB_PSICOLOGIA_AVALIACAO (
    ID_AVALIACAO             NUMBER(10) PRIMARY KEY,
    ID_PSICOLOGIA_DOC        NUMBER(10) NOT NULL UNIQUE,
    DS_TIPO_TESTE            VARCHAR2(100),  -- WISC, WAIS, RORSCHACH, etc
    DS_RESULTADO             VARCHAR2(4000),
    NR_ESCORE                NUMBER(5, 2),
    DS_INTERPRETACAO         VARCHAR2(4000),
    DS_RECOMENDACOES         VARCHAR2(4000),
    ID_USUARIO_FEZ           NUMBER(10) NOT NULL,
    DT_REALIZACAO            TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    DT_CRIACAO               TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    DT_ATUALIZACAO           TIMESTAMP(6) WITH TIME ZONE,
    DS_STATUS                VARCHAR2(20) DEFAULT 'RASCUNHO' NOT NULL,
    
    CONSTRAINT FK_AVALIACAO_DOCS 
        FOREIGN KEY (ID_PSICOLOGIA_DOC) REFERENCES FAV_TB_PSICOLOGIA_DOCUMENTOS(ID_PSICOLOGIA_DOC) ON DELETE CASCADE,
    CONSTRAINT FK_AVALIACAO_USUARIO 
        FOREIGN KEY (ID_USUARIO_FEZ) REFERENCES FAV_TB_SILA_USUARIOS(ID_USUARIO),
    CONSTRAINT CHK_AVALIACAO_STATUS 
        CHECK (DS_STATUS IN ('RASCUNHO', 'FINALIZADO', 'ASSINADO'))
);

CREATE INDEX IDX_AVALIACAO_DOCS ON FAV_TB_PSICOLOGIA_AVALIACAO(ID_PSICOLOGIA_DOC);
CREATE INDEX IDX_AVALIACAO_TIPO ON FAV_TB_PSICOLOGIA_AVALIACAO(DS_TIPO_TESTE);
CREATE SEQUENCE SEQ_PSICOLOGIA_AVALIACAO INCREMENT BY 1 START WITH 1;

-- ============================================================================
-- 5. TABELA: FAV_TB_PSICOLOGIA_VERSOES (Histórico e Auditoria)
-- ============================================================================
CREATE TABLE FAV_TB_PSICOLOGIA_VERSOES (
    ID_VERSAO                NUMBER(10) PRIMARY KEY,
    ID_PSICOLOGIA_DOC        NUMBER(10) NOT NULL,
    NR_VERSAO                NUMBER(5) DEFAULT 1 NOT NULL,
    DS_CONTEUDO_ANTERIOR     VARCHAR2(4000),
    ID_USUARIO_EDITOU        NUMBER(10) NOT NULL,
    DT_EDICAO                TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    DS_MOTIVO_ALTERACAO      VARCHAR2(500),
    DS_CAMPO_ALTERADO        VARCHAR2(100),  -- Nome do campo que foi alterado
    
    CONSTRAINT FK_VERSAO_DOCS 
        FOREIGN KEY (ID_PSICOLOGIA_DOC) REFERENCES FAV_TB_PSICOLOGIA_DOCUMENTOS(ID_PSICOLOGIA_DOC) ON DELETE CASCADE,
    CONSTRAINT FK_VERSAO_USUARIO 
        FOREIGN KEY (ID_USUARIO_EDITOU) REFERENCES FAV_TB_SILA_USUARIOS(ID_USUARIO)
);

CREATE INDEX IDX_VERSAO_DOCS ON FAV_TB_PSICOLOGIA_VERSOES(ID_PSICOLOGIA_DOC);
CREATE INDEX IDX_VERSAO_DATA ON FAV_TB_PSICOLOGIA_VERSOES(DT_EDICAO);
CREATE SEQUENCE SEQ_PSICOLOGIA_VERSAO INCREMENT BY 1 START WITH 1;

-- ============================================================================
-- ÍNDICES ADICIONAIS PARA PERFORMANCE
-- ============================================================================
CREATE INDEX IDX_PSICOLOGIA_DOCS_ATIVO ON FAV_TB_PSICOLOGIA_DOCUMENTOS(FL_ATIVO);
CREATE INDEX IDX_PSICOLOGIA_DOCS_COMPOSITE ON FAV_TB_PSICOLOGIA_DOCUMENTOS(CD_PACIENTE, DS_TIPO_DOC, FL_ATIVO);

COMMIT;

-- ============================================================================
-- FIM DO SCRIPT
-- ============================================================================
