export { default as api } from './client'
export * from './authService'
export * from './userService'
export * from './exameService'
export * from './ptsService'
export * from './adminService'
export * from './psicologiaService'
