-- =========================================================================
-- Migração: Adiciona frequências intermediárias 750 Hz e 1500 Hz (via aérea)
-- Tabela: FAV_TB_SILA_RESULTADOS_AUDIO
-- Data: 2026-05-31
-- =========================================================================
-- Limiares de limiar auditivo (dB HL)
ALTER TABLE FAV_TB_SILA_RESULTADOS_AUDIO ADD OD_VA_750  NUMBER(5,1);
ALTER TABLE FAV_TB_SILA_RESULTADOS_AUDIO ADD OD_VA_1500 NUMBER(5,1);
ALTER TABLE FAV_TB_SILA_RESULTADOS_AUDIO ADD OE_VA_750  NUMBER(5,1);
ALTER TABLE FAV_TB_SILA_RESULTADOS_AUDIO ADD OE_VA_1500 NUMBER(5,1);

-- Flags de sem resposta (NR) por frequência
ALTER TABLE FAV_TB_SILA_RESULTADOS_AUDIO ADD OD_VA_750_NR  NUMBER(1) DEFAULT 0;
ALTER TABLE FAV_TB_SILA_RESULTADOS_AUDIO ADD OD_VA_1500_NR NUMBER(1) DEFAULT 0;
ALTER TABLE FAV_TB_SILA_RESULTADOS_AUDIO ADD OE_VA_750_NR  NUMBER(1) DEFAULT 0;
ALTER TABLE FAV_TB_SILA_RESULTADOS_AUDIO ADD OE_VA_1500_NR NUMBER(1) DEFAULT 0;

COMMIT;
