-- ============================================================================
-- SCRIPT PARA ADICIONAR DIAGNÓSTICOS DA SEÇÃO 01 DO PTS (ESPECIALIDADE = 8)
-- ============================================================================
-- 
-- TABELA: TB_FAV_DIAGNOSTICO_CERIV
-- COLUNA id_especialidade = 8
-- 
-- ============================================================================

INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 8, 'DEFICITS LEVE DAS FUNÇÃO VISUAIS DA ACUIDADE VISUAL PARA LONGE COM OS DOIS OLHOS.', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 8, 'DEFICITS MODERADO DAS FUNÇÃO VISUAIS DA ACUIDADE VISUAL PARA LONGE COM OS DOIS OLHOS.', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 8, 'DEFICITS  GRAVE DAS FUNÇÃO VISUAIS DA ACUIDADE VISUAL PARA LONGE COM OS DOIS OLHOS.', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 8, 'DEFICITS LEVE DAS FUNÇÃO VISUAIS DA ACUIDADE VISUAL PARA LONGE COM O OLHO DIREITO OU O ESQUERDO.', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 8, 'DEFICITS MODERADO DAS FUNÇÃO VISUAIS DA ACUIDADE VISUAL PARA LONGE COM O OLHO DIREITO OU O ESQUERDO.', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 8, 'DEFICITS GRAVE DAS FUNÇÃO VISUAIS DA ACUIDADE VISUAL PARA LONGE COM O OLHO DIREITO OU O ESQUERDO.', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 8, 'DEFICITS LEVE DAS FUNÇÃO VISUAIS DA ACUIDADE VISUAL PARA PERTO COM OS DOIS OLHOS.', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 8, 'DEFICITS MODERADO DAS FUNÇÃO VISUAIS DA ACUIDADE VISUAL PARA PERTO COM OS DOIS OLHOS.', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 8, 'DEFICITS  GRAVE DAS FUNÇÃO VISUAIS DA ACUIDADE VISUAL PARA PERTO COM OS DOIS OLHOS.', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 8, 'DEFICITS LEVE DAS FUNÇÃO VISUAIS DA ACUIDADE VISUAL PARA PERTO COM O OLHO DIREITO OU O ESQUERDO.', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 8, 'DEFICITS MODERADO DAS FUNÇÃO VISUAIS DA ACUIDADE VISUAL PARA PERTO COM O OLHO DIREITO OU O ESQUERDO.', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 8, 'DEFICITS GRAVE DAS FUNÇÃO VISUAIS DA ACUIDADE VISUAL PARA PERTO COM O OLHO DIREITO OU O ESQUERDO.', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 8, 'DEFICITS DAS FUNÇÕES VISUAIS DO CAMPO VISUAL', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 8, 'DÉFICIT DAS FUNÇÕES VISUAIS DA SENSIBILIDADE À LUZ', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 8, 'DÉFICIT DAS FUNÇÕES VISUAIS DA VISÃO DE CORES', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 8, 'DÉFICIT DAS FUNÇÕES VISUAIS DA SENSIBILIDADE AO CONTRASTE', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 8, 'DÉFICIT DAS FUNÇÕES VISUAIS DA QUALIDADE DA IMAGEM', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 8, 'AUSÊNCIA DE CONHECIMENTO PARA USO DE PRODUTOS E TECNOLOGIAS PARA A EDUCAÇÃO', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 8, 'AUSÊNCIA DE CONHECIMENTO PARA USO DE PRODUTOS E TECNOLOGIAS PARA O TRABALHO', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 8, 'DÉFICIT DE APRENDIZAGEM  ASSOCIADA A DEFICIÊNCIA VISUAL - IMITAR', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 8, 'DÉFICIT DE  APRENDIZAGEM  ASSOCIADA A DEFICIÊNCIA VISUAL - ENSAIR (REPETIR)', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 8, 'DÉFICIT DE APRENDIZAGEM BÁSICA ASSOCIADA A DEFICIÊNCIA VISUAL - APRENDER A LER', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 8, 'DÉFICIT DE APRENDIZAGEM BÁSICA ASSOCIADA A DEFICIÊNCIA VISUAL - APRENDER A ESCREVER', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 8, 'DÉFICIT DE APRENDIZAGEM BÁSICA ASSOCIADA A DEFICIÊNCIA VISUAL - APRENDER A CALCULAR', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 8, 'DÉFICIT DE  APRENDIZAGEM  ASSOCIADA A DEFICIÊNCIA VISUAL - ADQUIRIR COMPETÊNCIAS BÁSICAS', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 8, 'DÉFICIT DE  APRENDIZAGEM  ASSOCIADA A DEFICIÊNCIA VISUAL - ADQUIRIR COMPETÊNCIAS COMPLEXAS', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 8, 'DÉFICIT DE APRENDIZAGEM ASSOCIADA A DEFICIÊNCIA VISUAL - CONCENTRAR A ATENÇÃO', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 8, 'DÉFICIT DE APRENDIZAGEM ASSOCIADA A DEFICIÊNCIA VISUAL - PENSAR', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 8, 'DÉFICIT DE APRENDIZAGEM  ASSOCIADA A DEFICIÊNCIA VISUAL - LER', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 8, 'DÉFICIT DE APRENDIZAGEM ASSOCIADA A DEFICIÊNCIA VISUAL - ESCREVER', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 8, 'DÉFICIT DE APRENDIZAGEM ASSOCIADA A DEFICIÊNCIA VISUAL - CALCULAR', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 8, 'DÉFICIT DE APRENDIZAGEM ASSOCIADA A DEFICIÊNCIA VISUAL - RESOLVER PROBLEMAS MATEMÁTICOS SIMPLES', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 8, 'DÉFICIT DE APRENDIZAGEM ASSOCIADA A DEFICIÊNCIA VISUAL - RESOLVER PROBLEMAS MATEMÁTICOS COMPLEXOS', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 8, 'DIFICULDADE DE ANDAR', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 8, 'DIFICULDADES DE ANDAR DISTÂNCIAS CURTAS', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 8, 'DIFICULDADES DE ANDAR LONGAS', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 8, 'DIFICULDADES DE ANDAR SOBRE SUPERFÍCIES DIFERENTES', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 8, 'DIFICULDADES DE ANDAR CONTORNANDO OBSTÁCULOS', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 8, 'DIFICULDADES DE DESLOCAR-SE MOVENDO TODO O CORPO', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 8, 'DIFICULDADE DE DESLOCAMENTO DENTRO DE CASA', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 8, 'DIFICULDADE DE DESLOCAMENTO DENTRO DE OUTROS EDIFÍCIOS DIFERENTE DA CASA', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 8, 'DIFICULDADE DE DESLOCAMENTO EM AMBIENTES EXTERNOS', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 8, 'NECESSIDADES DE USO DE EQUIPAMENTO PARA DESLOCAMENTO/LOCOMOÇÃO', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 8, 'DIFICULDADE DE DESLOCAMENTO COM UTILIZAÇÃO DE TRANSPORTE', 'S');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, 8, 'DIFICULDADES DE DESLOCAR-SE UTILIZANDO TRANSPORTE', 'S');

COMMIT;
