-- ============================================================================
-- SCRIPT PARA ADICIONAR DIAGNÓSTICOS DA ESPECIALIDADE DE FONOAUDIOLOGIA
-- Tabela: TB_FAV_DIAGNOSTICO_CERIV
-- Verifica duplicidades antes de inserir.
-- ============================================================================

DECLARE
  -- ID da Especialidade de Fonoaudiologia. 
  -- Em algumas bases é 1 (Diagnósticos/ESPECIALID), em outras pode variar. 
  -- Ajustar conforme necessário para a base de produção se não for 1.
  v_id_especialidade NUMBER := 1; 
  v_count NUMBER;
  v_col_count NUMBER;
BEGIN
  -- Verifica se a coluna ID_DIAGNOSTICO existe na tabela (Produção x Mock Local)
  SELECT count(*) INTO v_col_count 
  FROM user_tab_columns 
  WHERE table_name = 'TB_FAV_DIAGNOSTICO_CERIV' 
    AND column_name = 'ID_DIAGNOSTICO';

  FOR r IN (
    SELECT 'DISFAGIA OROFARINGEA GRAVE(PADPED)' AS diag FROM DUAL UNION ALL
    SELECT 'DISFAGIA OROFARINGEA MODERADA À GRAVE (PADPED)' FROM DUAL UNION ALL
    SELECT 'HIPERSENSIBILIDADE OROFACIAL' FROM DUAL UNION ALL
    SELECT 'LINGUAGEM ECOLALICA' FROM DUAL UNION ALL
    SELECT 'LARINGOMALACIA' FROM DUAL UNION ALL
    SELECT 'ANQUILOGLOSSIA' FROM DUAL UNION ALL
    SELECT 'PERDA AUDITIVA LEVE' FROM DUAL UNION ALL
    SELECT 'PERDA AUDITIVA MODERADA À SEVERA' FROM DUAL UNION ALL
    SELECT 'PERDA AUDITIVA PROFUNDA' FROM DUAL UNION ALL
    SELECT 'APRAXIA ORAL E APRAXIA DE FALA' FROM DUAL UNION ALL
    SELECT 'APRAXIA ORAL E DISARTRIA' FROM DUAL UNION ALL
    SELECT 'APRAXIA DE FALA NA INFÂNCIA' FROM DUAL UNION ALL
    SELECT 'APRAXIA E DISARTRIA' FROM DUAL UNION ALL
    SELECT 'AFASIA DE BROCA' FROM DUAL UNION ALL
    SELECT 'AFASIA DE WERNICK' FROM DUAL UNION ALL
    SELECT 'TDL TRANSTORNO DO DESENVOLVIMENTO DA LINGUAGEM' FROM DUAL UNION ALL
    SELECT 'TL TRANSTORNO DE LINGUAGEM' FROM DUAL UNION ALL
    SELECT 'TRANSTORNO FONOLÓGICO' FROM DUAL UNION ALL
    SELECT 'TRANSTORNO ESPECIFICO DA ARTICULAÇÃO DA FALA' FROM DUAL UNION ALL
    SELECT 'TRANSTORNO DOS SONS DA FALA' FROM DUAL UNION ALL
    SELECT 'TRANSTORNO MOTOR DA FALA' FROM DUAL UNION ALL
    SELECT 'TRANSTORNO EXPRESSIVO DE LINGUAGEM' FROM DUAL UNION ALL
    SELECT 'TRANSTORNO RECEPTIVO DA LINGUAGEM' FROM DUAL UNION ALL
    SELECT 'AFASIA ADQUIRIDA COM EPILEPSIA' FROM DUAL UNION ALL
    SELECT 'OUTROS TRANSTORNOS DE DESENVOLVIMENTO DA FALA OU LINGUAGEM' FROM DUAL UNION ALL
    SELECT 'TRANSTORNOS NÃO ESPECIFICADO DO DESENVOLVIMENTO DA FALA OU LINGUAGEM' FROM DUAL UNION ALL
    SELECT 'ATRASO DE LINGUAGEM ORAL' FROM DUAL UNION ALL
    SELECT 'ATRASO DE LINGUAGEM ESCRITA' FROM DUAL UNION ALL
    SELECT 'MUTISMO SELETIVO' FROM DUAL UNION ALL
    SELECT 'ATRASO MOTOR DE FALA' FROM DUAL UNION ALL
    SELECT 'ALTERAÇÃO DO SISTEMA SENSÓRIO MOTOR ORAL - SSMO' FROM DUAL UNION ALL
    SELECT 'ALTERAÇÃO NO SISTEMA ESTOMATOGNATICO' FROM DUAL UNION ALL
    SELECT 'DESVIO FONÉTICO' FROM DUAL UNION ALL
    SELECT 'DISATRIA' FROM DUAL UNION ALL
    SELECT 'DISFAGIA - NIVEL 1 - ESCALA FOIS' FROM DUAL UNION ALL
    SELECT 'DISFAGIA - NIVEL 2 - ESCALA FOIS' FROM DUAL UNION ALL
    SELECT 'DISFAGIA - NIVEL 3 - ESCALA FOIS' FROM DUAL UNION ALL
    SELECT 'DISFAGIA - NIVEL 4 - ESCALA FOIS' FROM DUAL UNION ALL
    SELECT 'DISFAGIA - NIVEL 5 - ESCALA FOIS' FROM DUAL UNION ALL
    SELECT 'DISFAGIA - NIVEL 6 - ESCALA FOIS' FROM DUAL UNION ALL
    SELECT 'DISFAGIA - NIVEL 7 - ESCALA FOIS' FROM DUAL UNION ALL
    SELECT 'DISFAGIA OROFARINGEA LEVE (PADPED)' FROM DUAL UNION ALL
    SELECT 'DISFLUENCIAS' FROM DUAL UNION ALL
    SELECT 'SINDROME DE SOTOS Q 83.7' FROM DUAL UNION ALL
    SELECT 'TRASTORNOS GLOBAIS NÃO ESPECIFICADOS DO DESENVOLVIMENTO' FROM DUAL UNION ALL
    SELECT 'TRANSTORNO DE LINGUAGEM' FROM DUAL UNION ALL
    SELECT 'PERDA AUDITIVA INDUZIDA POR RUÍDO' FROM DUAL UNION ALL
    SELECT 'SURDEZ A ISQUEMIA TRANSITÓRIA' FROM DUAL UNION ALL
    SELECT 'PERDA DE AUDIÇÃO BILATERAL DEVIDA A TRANSTORNO DE CONDUÇÃO' FROM DUAL UNION ALL
    SELECT 'PERDA DE AUDIÇÃO UNILATERAL POR TRANSTORNO DE CONDUÇÃO, SEM RESTRIÇÃO DE AUDIÇÃO CONTRALATERAL' FROM DUAL UNION ALL
    SELECT 'PERDA NÃO ESPECIFICADA DE AUDIÇÃO DEVIDA A TRANSTORNO DE CONDUÇÃO' FROM DUAL UNION ALL
    SELECT 'PERDA DE AUDIÇÃO BILATERAL NEURO-SENSORIAL' FROM DUAL UNION ALL
    SELECT 'PERDA DE AUDIÇÃO UNILATERAL NEURO-SENSORIAL, SEM RESTRIÇÃO DE AUDIÇÃO CONTRALATERAL' FROM DUAL UNION ALL
    SELECT 'PERDA DE AUDIÇÃO NEURO-SENSORIAL NÃO ESPECIFICADA' FROM DUAL UNION ALL
    SELECT 'PERDA DE AUDIÇÃO BILATERAL MISTA, DE CONDUÇÃO E NEURO-SENSORIAL, NÃO ESPECIFICADA' FROM DUAL UNION ALL
    SELECT 'PERDA DE AUDIÇÃO UNILATERAL MISTA DE CONDUÇÃO E NEURO-SENSORIAL, SEM RESTRIÇÃO DE AUDIÇÃO CONTRALATERAL' FROM DUAL UNION ALL
    SELECT 'PERDA DE AUDIÇÃO MISTA, DE CONDUÇÃO E NEURO-SENSORIAL, NÃO ESPECIFICADA' FROM DUAL UNION ALL
    SELECT 'OUTRAS PERDA DE AUDIÇÃO' FROM DUAL UNION ALL
    SELECT 'PERDA DE AUDIÇÃO OTOTÓXICA' FROM DUAL UNION ALL
    SELECT 'PERDA DE AUDIÇÃO SÚBITA IDIOPÁTICA' FROM DUAL UNION ALL
    SELECT 'OUTRAS PERDAS DE AUDIÇÃO ESPECIFICADAS' FROM DUAL UNION ALL
    SELECT 'PERDA NÃO ESPECIFICADA DE AUDIÇÃO (alta e baixa frequência)' FROM DUAL UNION ALL
    SELECT 'PERDA DE AUDIÇÃO POR TRANSTORNO DE CONDUÇÃO E/OU NEUROSSENSORIAL' FROM DUAL
  ) LOOP
    -- Verifica se o diagnóstico já existe para essa especialidade (case insensitive e removendo espaços)
    SELECT COUNT(*) INTO v_count 
    FROM TB_FAV_DIAGNOSTICO_CERIV 
    WHERE id_especialidade = v_id_especialidade 
      AND UPPER(TRIM(ds_diagnostico)) = UPPER(TRIM(r.diag));

    IF v_count = 0 THEN
      IF v_col_count > 0 THEN
        -- Banco real (MV) com sequência e IC_ATIVO
        EXECUTE IMMEDIATE 'INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (ID_DIAGNOSTICO, ID_ESPECIALIDADE, DS_DIAGNOSTICO, IC_ATIVO) VALUES (SEQ_FAV_DIAGNOSTICO_CERIV.NEXTVAL, :1, :2, ''S'')' USING v_id_especialidade, r.diag;
      ELSE
        -- Banco local (Mock)
        EXECUTE IMMEDIATE 'INSERT INTO TB_FAV_DIAGNOSTICO_CERIV (id_especialidade, ds_diagnostico) VALUES (:1, :2)' USING v_id_especialidade, r.diag;
      END IF;
    END IF;
  END LOOP;
END;
/
COMMIT;
