-- =========================================================================
-- MOCK DAS TABELAS EXTERNAS DO MV PARA O AMBIENTE DE TESTES
-- Removemos os prefixos DBAMV. e DBASGU. para facilitar no container local
-- =========================================================================

SET SQLBLANKLINES ON;


CREATE TABLE FAV_TB_SILA_USUARIOS (
    ID_USUARIO NUMBER(10) PRIMARY KEY,
    CD_USUARIO_MV VARCHAR2(50),
    NM_LOGIN VARCHAR2(50),
    NM_USUARIO VARCHAR2(100),
    DS_EMAIL VARCHAR2(100),
    DS_PERFIL VARCHAR2(50),
    DT_CRIACAO DATE,
    FL_ATIVO NUMBER(1)
);

CREATE TABLE USUARIOS (
    CD_USUARIO VARCHAR2(50) PRIMARY KEY,
    CD_PRESTADOR NUMBER
);

CREATE TABLE ATENDIME (
    CD_ATENDIMENTO NUMBER PRIMARY KEY,
    CD_PACIENTE NUMBER,
    DT_ATENDIMENTO DATE,
    CD_ORI_ATE NUMBER,
    CD_CONVENIO NUMBER,
    CD_MULTI_EMPRESA NUMBER
);

CREATE TABLE ITEM_AGENDAMENTO (
    CD_ITEM_AGENDAMENTO NUMBER PRIMARY KEY,
    DS_ITEM_AGENDAMENTO VARCHAR2(255),
    TP_ITEM VARCHAR2(1),
    CD_PROCEDIMENTO_SIA VARCHAR2(50),
    CD_EXA_RX NUMBER,
    CD_EXA_LAB NUMBER
);

CREATE TABLE EXA_RX (
    CD_EXA_RX NUMBER PRIMARY KEY,
    CD_PROCEDIMENTO_SIA VARCHAR2(50)
);

CREATE TABLE EXA_LAB (
    CD_EXA_LAB NUMBER PRIMARY KEY,
    CD_PROCEDIMENTO_SIA VARCHAR2(50)
);

CREATE SEQUENCE SEQ_FILA_ESP START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_FAV_LISTA_ESPERA START WITH 1 INCREMENT BY 1;

CREATE TABLE FAV_LISTA_ESPERA (
    CD_ID_FILA NUMBER,
    CD_ATENDIMENTO NUMBER,
    CD_PACIENTE NUMBER,
    CD_PROCEDIMENTO VARCHAR2(50),
    DT_ATENDIMENTO DATE,
    CD_PRESTADOR NUMBER,
    CD_ORI_ATE NUMBER,
    CD_CONVENIO NUMBER,
    CD_MULTI_EMPRESA NUMBER,
    OLHO VARCHAR2(10),
    CD_IT_AGEND NUMBER,
    TP_SITUACAO VARCHAR2(1),
    OBSERV VARCHAR2(4000),
    DT_LANCA_LISTA DATE,
    CD_LISTA_ESPERA NUMBER,
    CD_DOCUMENTO NUMBER,
    CD_PERG_OD VARCHAR2(50),
    CD_PERG_OE VARCHAR2(50),
    DT_RETORNO DATE,
    SN_COTA VARCHAR2(1),
    RESPOSTA_RETORNO VARCHAR2(4000),
    CER_PERIODIC VARCHAR2(50),
    CER_TP_GRUP VARCHAR2(50),
    CER_QT_GRUP VARCHAR2(50),
    CER_TOT_SES NUMBER,
    CER_SESSAO NUMBER
);


-- =========================================================================
-- ESTRUTURA DO PTS
-- =========================================================================

CREATE TABLE FAV_TB_PTS (
    ID_PTS                      NUMBER(10)      NOT NULL,
    CD_PACIENTE                 VARCHAR2(20)    NOT NULL,
    NR_ATENDIMENTO              VARCHAR2(20)    NOT NULL,
    ID_USUARIO                  NUMBER(10)      NOT NULL,
    DS_VIGENCIA                 CHAR(7)         NOT NULL,  
    DS_QUEIXA_PRINCIPAL         VARCHAR2(4000),
    FL_DEF_VISUAL               NUMBER(1)       DEFAULT 0 NOT NULL,
    FL_DEF_INTELECTUAL          NUMBER(1)       DEFAULT 0 NOT NULL,
    FL_DEF_FISICA               NUMBER(1)       DEFAULT 0 NOT NULL,
    FL_DEF_AUDITIVA             NUMBER(1)       DEFAULT 0 NOT NULL,
    FL_COND_NAO_SE_APLICA       NUMBER(1)       DEFAULT 0 NOT NULL,
    FL_COND_NAO_ESCUTA          NUMBER(1)       DEFAULT 0 NOT NULL,
    FL_COND_NAO_FALA            NUMBER(1)       DEFAULT 0 NOT NULL,
    FL_COND_NAO_ENXERGA         NUMBER(1)       DEFAULT 0 NOT NULL,
    FL_COND_AGITACAO            NUMBER(1)       DEFAULT 0 NOT NULL,
    FL_COND_AGRESSIVIDADE       NUMBER(1)       DEFAULT 0 NOT NULL,
    FL_COND_NAO_ANDA            NUMBER(1)       DEFAULT 0 NOT NULL,
    FL_COND_NAO_FICA_SOZINHO    NUMBER(1)       DEFAULT 0 NOT NULL,
    FL_COND_SEM_CTRL_CERVICAL   NUMBER(1)       DEFAULT 0 NOT NULL,
    FL_COND_SEM_CTRL_TRONCO     NUMBER(1)       DEFAULT 0 NOT NULL,
    DS_COND_OUTRA               VARCHAR2(500),
    FL_OPME_NAO_SE_APLICA       NUMBER(1)       DEFAULT 0 NOT NULL,
    FL_OPME_CADEIRA             NUMBER(1)       DEFAULT 0 NOT NULL,
    FL_OPME_BENGALA             NUMBER(1)       DEFAULT 0 NOT NULL,
    FL_OPME_MULETA              NUMBER(1)       DEFAULT 0 NOT NULL,
    FL_OPME_ANDADOR             NUMBER(1)       DEFAULT 0 NOT NULL,
    FL_OPME_PROTESE             NUMBER(1)       DEFAULT 0 NOT NULL,
    FL_OPME_COM_ALTA            NUMBER(1)       DEFAULT 0 NOT NULL,
    FL_OPME_COM_BAIXA           NUMBER(1)       DEFAULT 0 NOT NULL,
    FL_OPME_ORTESES             NUMBER(1)       DEFAULT 0 NOT NULL,
    DS_OPME_OUTROS              VARCHAR2(500),
    DS_CER_TERAPIAS_TEXTO       VARCHAR2(4000),
    FL_EXT_NAO_REALIZA          NUMBER(1)       DEFAULT 0 NOT NULL,
    DS_OBSERVACOES_GERAIS       CLOB,
    DS_CONDUTA_INTERDISCIPLINAR CLOB,
    DS_INTERVENCAO_PRAZO        VARCHAR2(200),
    DS_INTERVENCAO_DESCRICAO    CLOB,
    FL_PROG_NAO_SE_APLICA       NUMBER(1)       DEFAULT 0 NOT NULL,
    FL_PROG_GLAUCOMA            NUMBER(1)       DEFAULT 0 NOT NULL,
    FL_PROG_CATARATA            NUMBER(1)       DEFAULT 0 NOT NULL,
    FL_PROG_ALEM_OLHAR          NUMBER(1)       DEFAULT 0 NOT NULL,
    FL_PROG_ZIKA                NUMBER(1)       DEFAULT 0 NOT NULL,
    FL_PROG_APOIO_FAMILIAR      NUMBER(1)       DEFAULT 0 NOT NULL,
    FL_PROG_TEA                 NUMBER(1)       DEFAULT 0 NOT NULL,
    FL_PROG_INTERVENCAO_PRECOCE NUMBER(1)       DEFAULT 0 NOT NULL,
    FL_PROG_ROP                 NUMBER(1)       DEFAULT 0 NOT NULL,
    FL_PROG_PRONAS_TEA          NUMBER(1)       DEFAULT 0 NOT NULL,
    FL_PROG_PRONAS_DOENCAS_RARAS NUMBER(1)      DEFAULT 0 NOT NULL,
    FL_NAO_CONCLUIDO            NUMBER(1)       DEFAULT 0 NOT NULL,
    FL_FINALIZADO               NUMBER(1)       DEFAULT 0 NOT NULL,
    DT_CRIACAO                  DATE            DEFAULT SYSDATE NOT NULL,
    DT_ATUALIZACAO              DATE,
    FL_ATIVO                    NUMBER(1)       DEFAULT 1 NOT NULL,

    CONSTRAINT PK_PTS PRIMARY KEY (ID_PTS),
    CONSTRAINT FK_PTS_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES FAV_TB_SILA_USUARIOS (ID_USUARIO),
    CONSTRAINT UQ_PTS_PACIENTE_VIG UNIQUE (CD_PACIENTE, DS_VIGENCIA, ID_USUARIO, FL_ATIVO)
);

CREATE SEQUENCE SEQ_PTS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_PTS_BI
BEFORE INSERT ON FAV_TB_PTS FOR EACH ROW
BEGIN
    IF :NEW.ID_PTS IS NULL THEN
        SELECT SEQ_PTS.NEXTVAL INTO :NEW.ID_PTS FROM DUAL;
    END IF;
    :NEW.DT_CRIACAO := SYSDATE;
END;
/

CREATE OR REPLACE TRIGGER TRG_PTS_BU
BEFORE UPDATE ON FAV_TB_PTS FOR EACH ROW
BEGIN
    :NEW.DT_ATUALIZACAO := SYSDATE;
END;
/

-- Diagnósticos principais
CREATE TABLE FAV_TB_PTS_DIAG_PRINCIPAL (
    ID_DIAG_PRINCIPAL NUMBER(10)  NOT NULL,
    ID_PTS            NUMBER(10)  NOT NULL,
    NR_ORDEM          NUMBER(3)   DEFAULT 1 NOT NULL,
    DS_DIAGNOSTICO    VARCHAR2(500) NOT NULL,
    CONSTRAINT PK_PTS_DIAG_PRINC PRIMARY KEY (ID_DIAG_PRINCIPAL),
    CONSTRAINT FK_PTS_DPRINC FOREIGN KEY (ID_PTS) REFERENCES FAV_TB_PTS (ID_PTS) ON DELETE CASCADE
);
CREATE SEQUENCE SEQ_PTS_DIAG_PRINC START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE OR REPLACE TRIGGER TRG_PTS_DPRINC_BI BEFORE INSERT ON FAV_TB_PTS_DIAG_PRINCIPAL FOR EACH ROW
BEGIN IF :NEW.ID_DIAG_PRINCIPAL IS NULL THEN SELECT SEQ_PTS_DIAG_PRINC.NEXTVAL INTO :NEW.ID_DIAG_PRINCIPAL FROM DUAL; END IF; END;
/

-- Diagnóstico por área
CREATE TABLE FAV_TB_PTS_DIAG_AREA (
    ID_DIAG_AREA   NUMBER(10)   NOT NULL,
    ID_PTS         NUMBER(10)   NOT NULL,
    DS_AREA        VARCHAR2(20) NOT NULL,   
    DS_DIAGNOSTICO VARCHAR2(500),
    DS_GRAU        VARCHAR2(200),
    CONSTRAINT PK_PTS_DIAG_AREA PRIMARY KEY (ID_DIAG_AREA),
    CONSTRAINT FK_PTS_DAREA     FOREIGN KEY (ID_PTS) REFERENCES FAV_TB_PTS (ID_PTS) ON DELETE CASCADE,
    CONSTRAINT UQ_PTS_DAREA     UNIQUE (ID_PTS, DS_AREA)
);
CREATE SEQUENCE SEQ_PTS_DIAG_AREA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE OR REPLACE TRIGGER TRG_PTS_DAREA_BI BEFORE INSERT ON FAV_TB_PTS_DIAG_AREA FOR EACH ROW
BEGIN IF :NEW.ID_DIAG_AREA IS NULL THEN SELECT SEQ_PTS_DIAG_AREA.NEXTVAL INTO :NEW.ID_DIAG_AREA FROM DUAL; END IF; END;
/

-- Diagnósticos terapêuticos
CREATE TABLE FAV_TB_PTS_DIAG_TERAPEUTICO (
    ID_DIAG_TERAPEUTICO NUMBER(10)   NOT NULL,
    ID_PTS              NUMBER(10)   NOT NULL,
    NR_ORDEM            NUMBER(3)    DEFAULT 1 NOT NULL,
    DS_DIAGNOSTICO      VARCHAR2(500) NOT NULL,
    CONSTRAINT PK_PTS_DIAG_TERAP PRIMARY KEY (ID_DIAG_TERAPEUTICO),
    CONSTRAINT FK_PTS_DTERAP      FOREIGN KEY (ID_PTS) REFERENCES FAV_TB_PTS (ID_PTS) ON DELETE CASCADE
);
CREATE SEQUENCE SEQ_PTS_DIAG_TERAP START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE OR REPLACE TRIGGER TRG_PTS_DTERAP_BI BEFORE INSERT ON FAV_TB_PTS_DIAG_TERAPEUTICO FOR EACH ROW
BEGIN IF :NEW.ID_DIAG_TERAPEUTICO IS NULL THEN SELECT SEQ_PTS_DIAG_TERAP.NEXTVAL INTO :NEW.ID_DIAG_TERAPEUTICO FROM DUAL; END IF; END;
/

-- Serviços externos CER
CREATE TABLE FAV_TB_PTS_CER_TERAPIA (
    ID_CER_TERAPIA NUMBER(10)    NOT NULL,
    ID_PTS         NUMBER(10)    NOT NULL,
    DS_GRUPO       VARCHAR2(30)  NOT NULL,  
    NR_ORDEM       NUMBER(3)     DEFAULT 1 NOT NULL,
    DS_DIAGNOSTICO VARCHAR2(500) NOT NULL,
    CONSTRAINT PK_PTS_CER_TERAP PRIMARY KEY (ID_CER_TERAPIA),
    CONSTRAINT FK_PTS_CERTERAP   FOREIGN KEY (ID_PTS) REFERENCES FAV_TB_PTS (ID_PTS) ON DELETE CASCADE
);
CREATE SEQUENCE SEQ_PTS_CER_TERAP START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE OR REPLACE TRIGGER TRG_PTS_CERTERAP_BI BEFORE INSERT ON FAV_TB_PTS_CER_TERAPIA FOR EACH ROW
BEGIN IF :NEW.ID_CER_TERAPIA IS NULL THEN SELECT SEQ_PTS_CER_TERAP.NEXTVAL INTO :NEW.ID_CER_TERAPIA FROM DUAL; END IF; END;
/

-- Conduta Avaliação Médica
CREATE TABLE FAV_TB_PTS_CONDUTA_MED (
    ID_CONDUTA_MED   NUMBER(10)   NOT NULL,
    ID_PTS           NUMBER(10)   NOT NULL,
    NR_ORDEM         NUMBER(3)    DEFAULT 1 NOT NULL,
    CD_ESPECIALIDADE VARCHAR2(20) NOT NULL,
    DS_ESPECIALIDADE VARCHAR2(200),
    CONSTRAINT PK_PTS_CONDUTA_MED PRIMARY KEY (ID_CONDUTA_MED),
    CONSTRAINT FK_PTS_CONDMED     FOREIGN KEY (ID_PTS) REFERENCES FAV_TB_PTS (ID_PTS) ON DELETE CASCADE
);
CREATE SEQUENCE SEQ_PTS_CONDUTA_MED START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE OR REPLACE TRIGGER TRG_PTS_CONDMED_BI BEFORE INSERT ON FAV_TB_PTS_CONDUTA_MED FOR EACH ROW
BEGIN IF :NEW.ID_CONDUTA_MED IS NULL THEN SELECT SEQ_PTS_CONDUTA_MED.NEXTVAL INTO :NEW.ID_CONDUTA_MED FROM DUAL; END IF; END;
/

-- Conduta Multidisciplinar
CREATE TABLE FAV_TB_PTS_CONDUTA_MULTI (
    ID_CONDUTA_MULTI NUMBER(10)   NOT NULL,
    ID_PTS           NUMBER(10)   NOT NULL,
    NR_ORDEM         NUMBER(3)    DEFAULT 1 NOT NULL,
    CD_ITEM          VARCHAR2(20) NOT NULL,
    DS_ITEM          VARCHAR2(200),
    CONSTRAINT PK_PTS_CONDUTA_MULTI PRIMARY KEY (ID_CONDUTA_MULTI),
    CONSTRAINT FK_PTS_CONDMULTI    FOREIGN KEY (ID_PTS) REFERENCES FAV_TB_PTS (ID_PTS) ON DELETE CASCADE
);
CREATE SEQUENCE SEQ_PTS_CONDUTA_MULTI START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE OR REPLACE TRIGGER TRG_PTS_CONDMULTI_BI BEFORE INSERT ON FAV_TB_PTS_CONDUTA_MULTI FOR EACH ROW
BEGIN IF :NEW.ID_CONDUTA_MULTI IS NULL THEN SELECT SEQ_PTS_CONDUTA_MULTI.NEXTVAL INTO :NEW.ID_CONDUTA_MULTI FROM DUAL; END IF; END;
/

-- Instrumentos de avaliação
CREATE TABLE FAV_TB_PTS_INSTRUMENTO (
    ID_INSTRUMENTO NUMBER(10)    NOT NULL,
    ID_PTS         NUMBER(10)    NOT NULL,
    NR_ORDEM       NUMBER(3)     DEFAULT 1 NOT NULL,
    CD_INSTRUMENTO VARCHAR2(20),           
    DS_INSTRUMENTO VARCHAR2(500) NOT NULL,  
    CONSTRAINT PK_PTS_INSTRUMENTO PRIMARY KEY (ID_INSTRUMENTO),
    CONSTRAINT FK_PTS_INSTRUMENTO FOREIGN KEY (ID_PTS) REFERENCES FAV_TB_PTS (ID_PTS) ON DELETE CASCADE
);
CREATE SEQUENCE SEQ_PTS_INSTRUMENTO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE OR REPLACE TRIGGER TRG_PTS_INSTR_BI BEFORE INSERT ON FAV_TB_PTS_INSTRUMENTO FOR EACH ROW
BEGIN IF :NEW.ID_INSTRUMENTO IS NULL THEN SELECT SEQ_PTS_INSTRUMENTO.NEXTVAL INTO :NEW.ID_INSTRUMENTO FROM DUAL; END IF; END;
/

-- Objetivos
CREATE TABLE FAV_TB_PTS_OBJETIVO (
    ID_OBJETIVO      NUMBER(10)    NOT NULL,
    ID_PTS           NUMBER(10)    NOT NULL,
    DS_VIGENCIA      CHAR(7)       NOT NULL,   
    DS_ESPECIALIDADE VARCHAR2(30)  NOT NULL,
    DS_MOMENTO       VARCHAR2(10)  NOT NULL,   
    NR_ITEM          NUMBER(1)     NOT NULL,   
    DS_OBJETIVO      VARCHAR2(500),
    DS_DESCRICAO     CLOB,
    DS_OUTROS        VARCHAR2(4000),
    DS_STATUS        VARCHAR2(20),             
    DS_MOTIVO        VARCHAR2(500),            

    CONSTRAINT PK_PTS_OBJETIVO PRIMARY KEY (ID_OBJETIVO),
    CONSTRAINT FK_PTS_OBJ FOREIGN KEY (ID_PTS)
        REFERENCES FAV_TB_PTS (ID_PTS) ON DELETE CASCADE,
    CONSTRAINT UQ_PTS_OBJ UNIQUE (ID_PTS, DS_ESPECIALIDADE, DS_MOMENTO, NR_ITEM),
    CONSTRAINT CK_PTS_OBJ_MOMENTO CHECK (DS_MOMENTO IN ('anterior', 'atual')),
    CONSTRAINT CK_PTS_OBJ_STATUS  CHECK (DS_STATUS IN
        ('ALCANCADO', 'PARCIAL', 'NAO_ALCANCADO', 'NAO_SE_APLICA') OR DS_STATUS IS NULL),
    CONSTRAINT CK_PTS_OBJ_MOTIVO  CHECK (
        DS_MOTIVO IS NULL OR DS_STATUS IN ('PARCIAL', 'NAO_ALCANCADO')
    )
);
CREATE SEQUENCE SEQ_PTS_OBJETIVO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE OR REPLACE TRIGGER TRG_PTS_OBJ_BI
BEFORE INSERT ON FAV_TB_PTS_OBJETIVO FOR EACH ROW
BEGIN
    IF :NEW.ID_OBJETIVO IS NULL THEN
        SELECT SEQ_PTS_OBJETIVO.NEXTVAL INTO :NEW.ID_OBJETIVO FROM DUAL;
    END IF;
END;
/

-- Terapias
CREATE TABLE FAV_TB_PTS_TERAPIA (
    ID_TERAPIA          NUMBER(10)  NOT NULL,
    ID_PTS              NUMBER(10)  NOT NULL,
    NR_ORDEM            NUMBER(3)   DEFAULT 1 NOT NULL,
    CD_TERAPIA          VARCHAR2(20) NOT NULL,
    DS_TERAPIA          VARCHAR2(200),
    CD_TIPO_ATENDIMENTO VARCHAR2(5),
    DS_TIPO_ATENDIMENTO VARCHAR2(50),
    CD_PERIODICIDADE    VARCHAR2(5),
    DS_PERIODICIDADE    VARCHAR2(50),
    NR_QTDE_SESSOES     NUMBER(5),
    CONSTRAINT PK_PTS_TERAPIA PRIMARY KEY (ID_TERAPIA),
    CONSTRAINT FK_PTS_TERAP   FOREIGN KEY (ID_PTS) REFERENCES FAV_TB_PTS (ID_PTS) ON DELETE CASCADE
);
CREATE SEQUENCE SEQ_PTS_TERAPIA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE OR REPLACE TRIGGER TRG_PTS_TERAP_BI BEFORE INSERT ON FAV_TB_PTS_TERAPIA FOR EACH ROW
BEGIN IF :NEW.ID_TERAPIA IS NULL THEN SELECT SEQ_PTS_TERAPIA.NEXTVAL INTO :NEW.ID_TERAPIA FROM DUAL; END IF; END;
/

-- =========================================================================
-- PROCEDURES
-- =========================================================================

-- PROCEDURE: Insere terapias do PTS na fila de espera
CREATE OR REPLACE PROCEDURE PRC_FAV_PTS_INSERE_FILA (
    p_id_pts       IN FAV_TB_PTS.ID_PTS%TYPE,
    p_cd_prestador IN NUMBER
)
AS
    v_nr_atendimento  FAV_TB_PTS.NR_ATENDIMENTO%TYPE;
    v_cd_atendimento  NUMBER;
    v_cd_documento    CONSTANT NUMBER := 701;

    v_qtde_loop  NUMBER;
    v_qt_total   NUMBER;
    v_existe     NUMBER;

    CURSOR c_terapias IS
        SELECT t.CD_TERAPIA,
               t.DS_TERAPIA,
               t.CD_TIPO_ATENDIMENTO,
               t.DS_TIPO_ATENDIMENTO,
               t.DS_PERIODICIDADE,
               t.NR_QTDE_SESSOES
          FROM FAV_TB_PTS_TERAPIA t
         WHERE t.ID_PTS = p_id_pts
           AND t.CD_TERAPIA IS NOT NULL
           AND t.NR_QTDE_SESSOES > 0;

BEGIN
    SELECT NR_ATENDIMENTO
      INTO v_nr_atendimento
      FROM FAV_TB_PTS
     WHERE ID_PTS = p_id_pts;

    v_cd_atendimento := TO_NUMBER(v_nr_atendimento);

    FOR r IN c_terapias LOOP

        UPDATE FAV_LISTA_ESPERA le
           SET le.TP_SITUACAO = 'C',
               le.OBSERV      = 'Cancelado automático - Renovação PTS '
                                || TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI')
                                || NVL2(le.OBSERV, ' | Obs anterior: ' || le.OBSERV, '')
         WHERE le.CD_PACIENTE  = (SELECT a.CD_PACIENTE
                                    FROM ATENDIME a
                                   WHERE a.CD_ATENDIMENTO = v_cd_atendimento)
           AND le.CD_IT_AGEND  = TO_NUMBER(r.CD_TERAPIA)
           AND le.CD_DOCUMENTO = v_cd_documento
           AND le.TP_SITUACAO IN ('S', 'G', 'M');

        SELECT COUNT(*)
          INTO v_existe
          FROM FAV_LISTA_ESPERA le
         WHERE le.CD_DOCUMENTO = v_cd_documento
           AND le.CD_PACIENTE  = (SELECT a.CD_PACIENTE
                                    FROM ATENDIME a
                                   WHERE a.CD_ATENDIMENTO = v_cd_atendimento)
           AND le.CD_IT_AGEND  = TO_NUMBER(r.CD_TERAPIA)
           AND le.TP_SITUACAO  = 'S';

        IF v_existe <= 0 THEN

            v_qtde_loop := r.NR_QTDE_SESSOES;
            v_qt_total  := r.NR_QTDE_SESSOES;

            WHILE v_qtde_loop > 0 LOOP

                INSERT INTO FAV_LISTA_ESPERA (
                    CD_ID_FILA,
                    CD_ATENDIMENTO,
                    CD_PACIENTE,
                    CD_PROCEDIMENTO,
                    DT_ATENDIMENTO,
                    CD_PRESTADOR,
                    CD_ORI_ATE,
                    CD_CONVENIO,
                    CD_MULTI_EMPRESA,
                    OLHO,
                    CD_IT_AGEND,
                    TP_SITUACAO,
                    OBSERV,
                    DT_LANCA_LISTA,
                    CD_LISTA_ESPERA,
                    CD_DOCUMENTO,
                    CD_PERG_OD,
                    CD_PERG_OE,
                    DT_RETORNO,
                    SN_COTA,
                    RESPOSTA_RETORNO,
                    CER_PERIODIC,
                    CER_TP_GRUP,
                    CER_QT_GRUP,
                    CER_TOT_SES,
                    CER_SESSAO
                ) VALUES (
                    SEQ_FILA_ESP.NEXTVAL,
                    v_cd_atendimento,
                    (SELECT a.CD_PACIENTE      FROM ATENDIME a  WHERE a.CD_ATENDIMENTO = v_cd_atendimento),
                    (SELECT CASE ia.TP_ITEM
                                WHEN 'A' THEN ia.CD_PROCEDIMENTO_SIA
                                WHEN 'I' THEN (SELECT er.CD_PROCEDIMENTO_SIA FROM EXA_RX  er WHERE er.CD_EXA_RX  = ia.CD_EXA_RX)
                                WHEN 'L' THEN (SELECT el.CD_PROCEDIMENTO_SIA FROM EXA_LAB el WHERE el.CD_EXA_LAB = ia.CD_EXA_LAB)
                             END
                       FROM ITEM_AGENDAMENTO ia
                      WHERE ia.CD_ITEM_AGENDAMENTO = TO_NUMBER(r.CD_TERAPIA)),
                    (SELECT a.DT_ATENDIMENTO   FROM ATENDIME a  WHERE a.CD_ATENDIMENTO = v_cd_atendimento),
                    p_cd_prestador,
                    (SELECT a.CD_ORI_ATE       FROM ATENDIME a  WHERE a.CD_ATENDIMENTO = v_cd_atendimento),
                    (SELECT a.CD_CONVENIO      FROM ATENDIME a  WHERE a.CD_ATENDIMENTO = v_cd_atendimento),
                    (SELECT a.CD_MULTI_EMPRESA FROM ATENDIME a  WHERE a.CD_ATENDIMENTO = v_cd_atendimento),
                    NULL,
                    TO_NUMBER(r.CD_TERAPIA),
                    'S',
                    NULL,
                    SYSDATE,
                    SEQ_FAV_LISTA_ESPERA.NEXTVAL,
                    v_cd_documento,
                    NULL,
                    NULL,
                    NULL,
                    NULL,
                    NULL,
                    r.DS_PERIODICIDADE,
                    r.DS_TIPO_ATENDIMENTO,
                    r.CD_TIPO_ATENDIMENTO,
                    v_qt_total,
                    v_qtde_loop
                );

                v_qtde_loop := v_qtde_loop - 1;
            END LOOP;

        END IF;
    END LOOP;

EXCEPTION
    WHEN OTHERS THEN
        RAISE;
END PRC_FAV_PTS_INSERE_FILA;
/

-- PROCEDURE: Cancela na fila de espera todas as terapias de um PTS
CREATE OR REPLACE PROCEDURE PRC_FAV_PTS_CANCELA_FILA (
    p_id_pts  IN FAV_TB_PTS.ID_PTS%TYPE,
    p_motivo  IN VARCHAR2 DEFAULT 'Cancelado via PTS'
)
AS
    v_cd_atendimento NUMBER;
    v_cd_documento   CONSTANT NUMBER := 701;

BEGIN
    SELECT TO_NUMBER(NR_ATENDIMENTO)
      INTO v_cd_atendimento
      FROM FAV_TB_PTS
     WHERE ID_PTS = p_id_pts;

    UPDATE FAV_LISTA_ESPERA le
       SET le.TP_SITUACAO = 'C',
           le.OBSERV      = p_motivo
                            || ' - ' || TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI')
                            || NVL2(le.OBSERV, ' - ' || le.OBSERV, '')
     WHERE le.CD_DOCUMENTO   = v_cd_documento
       AND le.CD_ATENDIMENTO = v_cd_atendimento
       AND le.CD_IT_AGEND IN (
               SELECT TO_NUMBER(t.CD_TERAPIA)
                 FROM FAV_TB_PTS_TERAPIA t
                WHERE t.ID_PTS = p_id_pts
                  AND t.CD_TERAPIA IS NOT NULL
           )
       AND le.TP_SITUACAO IN ('S', 'G', 'M');

    UPDATE FAV_TB_PTS
       SET FL_ATIVO       = 0,
           DT_ATUALIZACAO = SYSDATE
     WHERE ID_PTS = p_id_pts;

EXCEPTION
    WHEN OTHERS THEN
        RAISE;
END PRC_FAV_PTS_CANCELA_FILA;
/


-- =========================================================================
-- DADOS MOCKADOS E DE DOMÍNIO
-- =========================================================================

CREATE TABLE TB_FAV_DIAGNOSTICO_CERIV (id_especialidade NUMBER, ds_diagnostico VARCHAR2(255));
CREATE TABLE ESPECIALID (cd_especialid NUMBER, ds_especialid VARCHAR2(255));
CREATE TABLE FAV_ITEM_CER4 (cd_item_agendamento NUMBER, ds_item_agendamento VARCHAR2(255), item_terapia VARCHAR2(1));
CREATE TABLE FAV_INSTR_AVAL_CER4 (seq NUMBER, instrumento VARCHAR2(255));

-- Inserindo o usuário testesoul base
INSERT INTO FAV_TB_SILA_USUARIOS (ID_USUARIO, CD_USUARIO_MV, NM_LOGIN, NM_USUARIO, DS_EMAIL, DS_PERFIL, DT_CRIACAO, FL_ATIVO)
VALUES (1, 'testesoul', 'testesoul', 'Usuário Teste Soul', 'teste@soul.com', 'OPERADOR', SYSDATE, 1);

INSERT INTO USUARIOS (CD_USUARIO, CD_PRESTADOR) VALUES ('testesoul', 999);

-- Inserindo Atendimento Mockado que será usado no script de mockup
-- No mock data, geramos NR_ATENDIMENTO aleatório, mas para funcionar com a procedure que busca CD_PACIENTE
-- pelo CD_ATENDIMENTO, precisaremos inserir os atendimentos na tabela ATENDIME no próprio script mock.
-- Deixaremos a tabela vazia aqui, e no mock_data.py iremos persistir o atendimento e paciente antes da procedure!

-- Especialidades
INSERT INTO ESPECIALID VALUES (1, 'Fonoaudiologia');
INSERT INTO ESPECIALID VALUES (2, 'Psicologia');
INSERT INTO ESPECIALID VALUES (3, 'Fisioterapia');
INSERT INTO ESPECIALID VALUES (4, 'Terapia Ocupacional');

-- Atendimento Dummy para testes via Frontend (Atendimento: 888888, Paciente: 999999)
INSERT INTO ATENDIME (CD_ATENDIMENTO, CD_PACIENTE, DT_ATENDIMENTO, CD_ORI_ATE, CD_CONVENIO, CD_MULTI_EMPRESA) 
VALUES (888888, 999999, SYSDATE, 1, 1, 1);

-- Diagnosticos
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (1, 'Atraso de Linguagem');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (1, 'Autismo');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (1, 'ALBINISMO OCULAR');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (1, 'ALTA MIOPIA');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (1, 'AMBLIOPIA');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (1, 'ANIRIDIA');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (1, 'ANOFTALMIA');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (1, 'ATROFIA GEOGRAFICA DA RETINA');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (1, 'BAIXA VISÃO');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (1, 'CATARATA');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (1, 'CATARATA CONGENITA');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (1, 'CATARATA INFANTIL');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (1, 'CEGUEIRA');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (1, 'CEGUEIRA CORTICAL');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (1, 'CERATOCONE');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (1, 'CICATRIZ DE MACULA');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (1, 'COLOBOMA DO NERVO ÓPTICO/RETINA');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (1, 'CORIORRETINITE');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (1, 'DEGENERAÇÃO MACULAR RELACIONADA A IDADE (DMRI)');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (1, 'DESLOCAMENTO DE RETINA');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (1, 'DISTROFIA DE RETINA');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (1, 'DOENÇA DE AICARDI');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (1, 'DOENÇA DE COATS');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (1, 'DOENÇA DE LYME');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (1, 'DOENÇA DE PETERS');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (1, 'DOENÇA DE STARGART');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (1, 'EM INVESTIGAÇÃO');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (1, 'ESTRABISMO');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (1, 'GLAUCOMA');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (1, 'GLAUCOMA CONGENITO');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (1, 'GLAUCOMA NEUROVASCULAR');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (1, 'GLIOMA DO NERVO ÓPTICO');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (1, 'HIPERMETROPIA ALTA');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (1, 'LESÃO NA CÓRNEA');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (1, 'MACULOPATIA');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (1, 'MAL FORMAÇÃO CONGENITA MÚLTIPLA (MFCM)');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (1, 'MICROCEFALIA');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (1, 'MICROCEFALIA PELO VIRUS DA ZIKA');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (1, 'MIOPIA DEGENERATIVA');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (1, 'NEURITE ÓPTICA');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (1, 'NISTAGMO');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (1, 'OPACIDADE CORNEANA');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (1, 'RETINOBLASTOMA');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (1, 'RETINOPATIA DA PREMATURIDADE - ROP');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (1, 'RETINOPATIA DIABETICA');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (1, 'RETINOSE PIGMENTAR');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (1, 'SEQUELA DE TUMOR CEREBRAL');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (1, 'SUBLUXAÇÃO DO CRISTALINO');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (1, 'TOXOCARIDÍASE');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (1, 'TOXOPLASMOSE');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (1, 'TRAUMA OCULAR');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (1, 'TRAUMA POR ARMA DE FOGO (PAF)');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (1, 'UVEITE');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (2, 'Ansiedade');
INSERT INTO TB_FAV_DIAGNOSTICO_CERIV VALUES (3, 'Paralisia Cerebral');

-- Itens e Terapias
INSERT INTO ITEM_AGENDAMENTO (CD_ITEM_AGENDAMENTO, DS_ITEM_AGENDAMENTO, TP_ITEM, CD_PROCEDIMENTO_SIA) VALUES (101, 'Avaliação Fonoaudiológica', 'A', '0301010048');
INSERT INTO ITEM_AGENDAMENTO (CD_ITEM_AGENDAMENTO, DS_ITEM_AGENDAMENTO, TP_ITEM, CD_PROCEDIMENTO_SIA) VALUES (102, 'Terapia Fonoaudiológica', 'A', '0301010048');
INSERT INTO ITEM_AGENDAMENTO (CD_ITEM_AGENDAMENTO, DS_ITEM_AGENDAMENTO, TP_ITEM, CD_PROCEDIMENTO_SIA) VALUES (103, 'Rastreio Auditivo', 'A', '0301010048');

INSERT INTO FAV_ITEM_CER4 VALUES (101, 'Avaliação Fonoaudiológica', 'N');
INSERT INTO FAV_ITEM_CER4 VALUES (102, 'Terapia Fonoaudiológica', 'S');
INSERT INTO FAV_ITEM_CER4 VALUES (103, 'Rastreio Auditivo', 'N');

-- Instrumentos
INSERT INTO FAV_INSTR_AVAL_CER4 VALUES (1, 'Protocolo de Observação Comportamental');
INSERT INTO FAV_INSTR_AVAL_CER4 VALUES (2, 'M-CHAT');

COMMIT;
-- =========================================================================
-- NOVAS TABELAS DE OBJETIVOS (BIBLIOTECA)
-- =========================================================================

CREATE TABLE FAV_TB_ESP_OBJETIVO_CERIV (
    ID_ESPECIALIDADE  NUMBER(5)    NOT NULL,
    DS_ESPECIALIDADE  VARCHAR2(80) NOT NULL,
    DT_CRIACAO        DATE         DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_ESP_OBJETIVO_CERIV PRIMARY KEY (ID_ESPECIALIDADE)
);

CREATE TABLE FAV_TB_OBJETIVO_CERIV (
    ID_OBJETIVO       NUMBER(6)     NOT NULL,
    ID_ESPECIALIDADE  NUMBER(5)     NOT NULL,
    DS_OBJETIVO       VARCHAR2(500) NOT NULL,
    IC_ATIVO          CHAR(1)       DEFAULT 'S' NOT NULL,
    DT_CRIACAO        DATE          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_OBJETIVO_CERIV     PRIMARY KEY (ID_OBJETIVO),
    CONSTRAINT FK_OBJ_ESP_CERIV      FOREIGN KEY (ID_ESPECIALIDADE) REFERENCES FAV_TB_ESP_OBJETIVO_CERIV(ID_ESPECIALIDADE),
    CONSTRAINT CK_OBJ_CERIV_ATIVO    CHECK (IC_ATIVO IN ('S','N'))
);

-- MOCK DATA PARA OBJETIVOS
INSERT INTO FAV_TB_ESP_OBJETIVO_CERIV (ID_ESPECIALIDADE, DS_ESPECIALIDADE) VALUES (1, 'FISIOTERAPIA');
INSERT INTO FAV_TB_ESP_OBJETIVO_CERIV (ID_ESPECIALIDADE, DS_ESPECIALIDADE) VALUES (2, 'FISIOTERAPIA AQU�TICA');
INSERT INTO FAV_TB_ESP_OBJETIVO_CERIV (ID_ESPECIALIDADE, DS_ESPECIALIDADE) VALUES (3, 'PSICOPEDAGOGIA');
INSERT INTO FAV_TB_ESP_OBJETIVO_CERIV (ID_ESPECIALIDADE, DS_ESPECIALIDADE) VALUES (4, 'TERAPIA OCUPACIONAL');
INSERT INTO FAV_TB_ESP_OBJETIVO_CERIV (ID_ESPECIALIDADE, DS_ESPECIALIDADE) VALUES (5, 'PSICOLOGIA');
INSERT INTO FAV_TB_ESP_OBJETIVO_CERIV (ID_ESPECIALIDADE, DS_ESPECIALIDADE) VALUES (6, 'PROFISSIONAL DE ED. F�SICA');

-- Fisioterapia
INSERT INTO FAV_TB_OBJETIVO_CERIV (ID_OBJETIVO, ID_ESPECIALIDADE, DS_OBJETIVO) VALUES (1, 1, 'DESENVOLVER A L�GICA E O RACIOC�NIO');
INSERT INTO FAV_TB_OBJETIVO_CERIV (ID_OBJETIVO, ID_ESPECIALIDADE, DS_OBJETIVO) VALUES (2, 1, 'Mover-se de p� sobre uma superf�cie, passo a passo');
INSERT INTO FAV_TB_OBJETIVO_CERIV (ID_OBJETIVO, ID_ESPECIALIDADE, DS_OBJETIVO) VALUES (3, 1, 'Andar dist�ncias curtas de menos de 1 km');

-- Psicopedagogia
INSERT INTO FAV_TB_OBJETIVO_CERIV (ID_OBJETIVO, ID_ESPECIALIDADE, DS_OBJETIVO) VALUES (10, 3, 'Ensino de habilidades b�sicas de linguagem expressiva');
INSERT INTO FAV_TB_OBJETIVO_CERIV (ID_OBJETIVO, ID_ESPECIALIDADE, DS_OBJETIVO) VALUES (11, 3, 'Estimular a reprodu��o motora e gr�fica de movimentos');

-- Terapia Ocupacional
INSERT INTO FAV_TB_OBJETIVO_CERIV (ID_OBJETIVO, ID_ESPECIALIDADE, DS_OBJETIVO) VALUES (20, 4, 'Desenvolver respostas adaptativas para est�mulos sensoriais');
INSERT INTO FAV_TB_OBJETIVO_CERIV (ID_OBJETIVO, ID_ESPECIALIDADE, DS_OBJETIVO) VALUES (21, 4, 'PROMOVER A PARTICIPA��O SOCIAL');

-- Psicologia
INSERT INTO FAV_TB_OBJETIVO_CERIV (ID_OBJETIVO, ID_ESPECIALIDADE, DS_OBJETIVO) VALUES (30, 5, 'APRENDER A HABILIDADE DE TROCA DE TURNO');
INSERT INTO FAV_TB_OBJETIVO_CERIV (ID_OBJETIVO, ID_ESPECIALIDADE, DS_OBJETIVO) VALUES (31, 5, 'AUMENTAR A TOLER�NCIA DE ESPERA');

-- Ed F�sica
INSERT INTO FAV_TB_OBJETIVO_CERIV (ID_OBJETIVO, ID_ESPECIALIDADE, DS_OBJETIVO) VALUES (40, 6, 'DESENVOLVER MARCHA');
INSERT INTO FAV_TB_OBJETIVO_CERIV (ID_OBJETIVO, ID_ESPECIALIDADE, DS_OBJETIVO) VALUES (41, 6, 'FORTALECIMENTO MUSCULAR DOS MMSS');

COMMIT;

-- =========================================================================
-- AJUSTE DAS ESPECIALIDADES PARA BATER COM O FRONTEND
-- =========================================================================

DELETE FROM FAV_TB_OBJETIVO_CERIV;
DELETE FROM FAV_TB_ESP_OBJETIVO_CERIV;

INSERT INTO FAV_TB_ESP_OBJETIVO_CERIV (ID_ESPECIALIDADE, DS_ESPECIALIDADE) VALUES (1, 'FISIOTERAPIA');
INSERT INTO FAV_TB_ESP_OBJETIVO_CERIV (ID_ESPECIALIDADE, DS_ESPECIALIDADE) VALUES (2, 'FISIOTERAPIA AQU�TICA');
INSERT INTO FAV_TB_ESP_OBJETIVO_CERIV (ID_ESPECIALIDADE, DS_ESPECIALIDADE) VALUES (3, 'PSICOPEDAGOGIA');
INSERT INTO FAV_TB_ESP_OBJETIVO_CERIV (ID_ESPECIALIDADE, DS_ESPECIALIDADE) VALUES (4, 'TERAPIA OCUPACIONAL');
INSERT INTO FAV_TB_ESP_OBJETIVO_CERIV (ID_ESPECIALIDADE, DS_ESPECIALIDADE) VALUES (5, 'PSICOLOGIA');
INSERT INTO FAV_TB_ESP_OBJETIVO_CERIV (ID_ESPECIALIDADE, DS_ESPECIALIDADE) VALUES (6, 'PROF. EDUCA��O F�SICA');
INSERT INTO FAV_TB_ESP_OBJETIVO_CERIV (ID_ESPECIALIDADE, DS_ESPECIALIDADE) VALUES (7, 'PSICOLOGIA SONORO MUSICAL');
INSERT INTO FAV_TB_ESP_OBJETIVO_CERIV (ID_ESPECIALIDADE, DS_ESPECIALIDADE) VALUES (8, 'PROFESSOR DE BRAILLE');
INSERT INTO FAV_TB_ESP_OBJETIVO_CERIV (ID_ESPECIALIDADE, DS_ESPECIALIDADE) VALUES (9, 'FONOAUDIOLOGIA');

-- Fisioterapia
INSERT INTO FAV_TB_OBJETIVO_CERIV (ID_OBJETIVO, ID_ESPECIALIDADE, DS_OBJETIVO) VALUES (1, 1, 'DESENVOLVER A L�GICA E O RACIOC�NIO');
INSERT INTO FAV_TB_OBJETIVO_CERIV (ID_OBJETIVO, ID_ESPECIALIDADE, DS_OBJETIVO) VALUES (2, 1, 'Mover-se de p� sobre uma superf�cie, passo a passo');
-- Objetivos do Psicopedagogo acrescentados em Fisioterapia
INSERT INTO FAV_TB_OBJETIVO_CERIV (ID_OBJETIVO, ID_ESPECIALIDADE, DS_OBJETIVO) VALUES (62, 1, 'Ensino de habilidades b�sicas de linguagem expressiva');
INSERT INTO FAV_TB_OBJETIVO_CERIV (ID_OBJETIVO, ID_ESPECIALIDADE, DS_OBJETIVO) VALUES (63, 1, 'Estimular a reprodu��o motora e gr�fica de movimentos');

-- Psicopedagogia
INSERT INTO FAV_TB_OBJETIVO_CERIV (ID_OBJETIVO, ID_ESPECIALIDADE, DS_OBJETIVO) VALUES (10, 3, 'Ensino de habilidades b�sicas de linguagem expressiva');
INSERT INTO FAV_TB_OBJETIVO_CERIV (ID_OBJETIVO, ID_ESPECIALIDADE, DS_OBJETIVO) VALUES (11, 3, 'Estimular a reprodu��o motora e gr�fica de movimentos');

-- Terapia Ocupacional
INSERT INTO FAV_TB_OBJETIVO_CERIV (ID_OBJETIVO, ID_ESPECIALIDADE, DS_OBJETIVO) VALUES (20, 4, 'Desenvolver respostas adaptativas para est�mulos sensoriais');
INSERT INTO FAV_TB_OBJETIVO_CERIV (ID_OBJETIVO, ID_ESPECIALIDADE, DS_OBJETIVO) VALUES (21, 4, 'PROMOVER A PARTICIPA��O SOCIAL');
-- Objetivos do Psicopedagogo acrescentados em Terapia Ocupacional
INSERT INTO FAV_TB_OBJETIVO_CERIV (ID_OBJETIVO, ID_ESPECIALIDADE, DS_OBJETIVO) VALUES (64, 4, 'Ensino de habilidades b�sicas de linguagem expressiva');
INSERT INTO FAV_TB_OBJETIVO_CERIV (ID_OBJETIVO, ID_ESPECIALIDADE, DS_OBJETIVO) VALUES (65, 4, 'Estimular a reprodu��o motora e gr�fica de movimentos');

-- Prof. Educa��o F�sica
INSERT INTO FAV_TB_OBJETIVO_CERIV (ID_OBJETIVO, ID_ESPECIALIDADE, DS_OBJETIVO) VALUES (40, 6, 'DESENVOLVER MARCHA');
INSERT INTO FAV_TB_OBJETIVO_CERIV (ID_OBJETIVO, ID_ESPECIALIDADE, DS_OBJETIVO) VALUES (41, 6, 'FORTALECIMENTO MUSCULAR DOS MMSS');

-- Psicologia Sonoro Musical
INSERT INTO FAV_TB_OBJETIVO_CERIV (ID_OBJETIVO, ID_ESPECIALIDADE, DS_OBJETIVO) VALUES (50, 7, 'ESTIMULAR PERCEP��O SONORA');
INSERT INTO FAV_TB_OBJETIVO_CERIV (ID_OBJETIVO, ID_ESPECIALIDADE, DS_OBJETIVO) VALUES (51, 7, 'DESENVOLVER RITMO E COORDENA��O');

-- Braille
INSERT INTO FAV_TB_OBJETIVO_CERIV (ID_OBJETIVO, ID_ESPECIALIDADE, DS_OBJETIVO) VALUES (60, 8, 'RECONHECER SINAIS BRAILLE');

-- Psicologia
INSERT INTO FAV_TB_OBJETIVO_CERIV (ID_OBJETIVO, ID_ESPECIALIDADE, DS_OBJETIVO) VALUES (30, 5, 'APRENDER A HABILIDADE DE TROCA DE TURNO');

COMMIT;
