-- =========================================================================
-- MIGRAÇÃO: Adiciona colunas NR por frequência na tabela de resultados de
-- audiometria. Executar manualmente no banco Oracle se já existir a tabela.
-- =========================================================================

-- VA OD
ALTER TABLE FAV_TB_SILA_RESULTADOS_AUDIO ADD OD_VA_250_NR  NUMBER(1) DEFAULT 0;
ALTER TABLE FAV_TB_SILA_RESULTADOS_AUDIO ADD OD_VA_500_NR  NUMBER(1) DEFAULT 0;
ALTER TABLE FAV_TB_SILA_RESULTADOS_AUDIO ADD OD_VA_1000_NR NUMBER(1) DEFAULT 0;
ALTER TABLE FAV_TB_SILA_RESULTADOS_AUDIO ADD OD_VA_2000_NR NUMBER(1) DEFAULT 0;
ALTER TABLE FAV_TB_SILA_RESULTADOS_AUDIO ADD OD_VA_3000_NR NUMBER(1) DEFAULT 0;
ALTER TABLE FAV_TB_SILA_RESULTADOS_AUDIO ADD OD_VA_4000_NR NUMBER(1) DEFAULT 0;
ALTER TABLE FAV_TB_SILA_RESULTADOS_AUDIO ADD OD_VA_6000_NR NUMBER(1) DEFAULT 0;
ALTER TABLE FAV_TB_SILA_RESULTADOS_AUDIO ADD OD_VA_8000_NR NUMBER(1) DEFAULT 0;

-- VO OD
ALTER TABLE FAV_TB_SILA_RESULTADOS_AUDIO ADD OD_VO_500_NR  NUMBER(1) DEFAULT 0;
ALTER TABLE FAV_TB_SILA_RESULTADOS_AUDIO ADD OD_VO_1000_NR NUMBER(1) DEFAULT 0;
ALTER TABLE FAV_TB_SILA_RESULTADOS_AUDIO ADD OD_VO_2000_NR NUMBER(1) DEFAULT 0;
ALTER TABLE FAV_TB_SILA_RESULTADOS_AUDIO ADD OD_VO_4000_NR NUMBER(1) DEFAULT 0;

-- VA OE
ALTER TABLE FAV_TB_SILA_RESULTADOS_AUDIO ADD OE_VA_250_NR  NUMBER(1) DEFAULT 0;
ALTER TABLE FAV_TB_SILA_RESULTADOS_AUDIO ADD OE_VA_500_NR  NUMBER(1) DEFAULT 0;
ALTER TABLE FAV_TB_SILA_RESULTADOS_AUDIO ADD OE_VA_1000_NR NUMBER(1) DEFAULT 0;
ALTER TABLE FAV_TB_SILA_RESULTADOS_AUDIO ADD OE_VA_2000_NR NUMBER(1) DEFAULT 0;
ALTER TABLE FAV_TB_SILA_RESULTADOS_AUDIO ADD OE_VA_3000_NR NUMBER(1) DEFAULT 0;
ALTER TABLE FAV_TB_SILA_RESULTADOS_AUDIO ADD OE_VA_4000_NR NUMBER(1) DEFAULT 0;
ALTER TABLE FAV_TB_SILA_RESULTADOS_AUDIO ADD OE_VA_6000_NR NUMBER(1) DEFAULT 0;
ALTER TABLE FAV_TB_SILA_RESULTADOS_AUDIO ADD OE_VA_8000_NR NUMBER(1) DEFAULT 0;

-- VO OE
ALTER TABLE FAV_TB_SILA_RESULTADOS_AUDIO ADD OE_VO_500_NR  NUMBER(1) DEFAULT 0;
ALTER TABLE FAV_TB_SILA_RESULTADOS_AUDIO ADD OE_VO_1000_NR NUMBER(1) DEFAULT 0;
ALTER TABLE FAV_TB_SILA_RESULTADOS_AUDIO ADD OE_VO_2000_NR NUMBER(1) DEFAULT 0;
ALTER TABLE FAV_TB_SILA_RESULTADOS_AUDIO ADD OE_VO_4000_NR NUMBER(1) DEFAULT 0;

COMMIT;
