-- =============================================================================
-- 10_tabelas_auditoria_logs.sql
-- Cria tabelas de auditoria e logs de sistema
-- Compatível com Oracle 11g/12c (nomes de objeto ≤ 30 caracteres)
-- =============================================================================

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. LOG DE AUDITORIA — registra operações em tabelas críticas
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE FAV_TB_LOG_AUDITORIA (
    ID_LOG               NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NM_TABELA            VARCHAR2(60)  NOT NULL,
    TP_OPERACAO          VARCHAR2(10)  NOT NULL,   -- INSERT | UPDATE | DELETE
    NM_LOGIN             VARCHAR2(50),
    NM_USUARIO           VARCHAR2(200),
    DT_OPERACAO          TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    DS_DESCRICAO         VARCHAR2(500),
    DS_VALORES_ANTERIORES CLOB,
    DS_VALORES_NOVOS      CLOB
);

COMMENT ON TABLE  FAV_TB_LOG_AUDITORIA              IS 'Log centralizado de auditoria do sistema';
COMMENT ON COLUMN FAV_TB_LOG_AUDITORIA.ID_LOG       IS 'Identificador único do log';
COMMENT ON COLUMN FAV_TB_LOG_AUDITORIA.NM_TABELA    IS 'Nome da tabela afetada pela operação';
COMMENT ON COLUMN FAV_TB_LOG_AUDITORIA.TP_OPERACAO  IS 'Tipo: INSERT, UPDATE ou DELETE';
COMMENT ON COLUMN FAV_TB_LOG_AUDITORIA.NM_LOGIN     IS 'Login do usuário que realizou a operação';
COMMENT ON COLUMN FAV_TB_LOG_AUDITORIA.DT_OPERACAO  IS 'Data/hora da operação';
COMMENT ON COLUMN FAV_TB_LOG_AUDITORIA.DS_DESCRICAO IS 'Descrição legível da operação';
COMMENT ON COLUMN FAV_TB_LOG_AUDITORIA.DS_VALORES_ANTERIORES IS 'Valores antes da alteração (JSON)';
COMMENT ON COLUMN FAV_TB_LOG_AUDITORIA.DS_VALORES_NOVOS      IS 'Valores após a alteração (JSON)';

-- Índices para consultas frequentes
CREATE INDEX IDX_LOG_AUDIT_TABELA   ON FAV_TB_LOG_AUDITORIA (NM_TABELA);
CREATE INDEX IDX_LOG_AUDIT_LOGIN    ON FAV_TB_LOG_AUDITORIA (NM_LOGIN);
CREATE INDEX IDX_LOG_AUDIT_DT       ON FAV_TB_LOG_AUDITORIA (DT_OPERACAO);
CREATE INDEX IDX_LOG_AUDIT_OP       ON FAV_TB_LOG_AUDITORIA (TP_OPERACAO);


-- ─────────────────────────────────────────────────────────────────────────────
-- 2. LOG DE SISTEMA — erros e exceções da aplicação backend
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE FAV_TB_LOG_SISTEMA (
    ID_LOG        NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TP_NIVEL      VARCHAR2(10)  NOT NULL,   -- ERROR | WARNING | INFO
    NM_MODULO     VARCHAR2(100),            -- ex: "auth", "pts", "exames"
    DS_MENSAGEM   VARCHAR2(2000) NOT NULL,
    DS_DETALHE    CLOB,                     -- stack trace ou contexto extra
    NM_LOGIN      VARCHAR2(50),
    DS_IP_ORIGEM  VARCHAR2(50),
    DT_CRIACAO    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

COMMENT ON TABLE  FAV_TB_LOG_SISTEMA            IS 'Log de erros e eventos do backend FastAPI';
COMMENT ON COLUMN FAV_TB_LOG_SISTEMA.TP_NIVEL   IS 'Nível: ERROR, WARNING ou INFO';
COMMENT ON COLUMN FAV_TB_LOG_SISTEMA.NM_MODULO  IS 'Módulo da aplicação que gerou o evento';
COMMENT ON COLUMN FAV_TB_LOG_SISTEMA.DS_DETALHE IS 'Stack trace ou detalhes adicionais do erro';

CREATE INDEX IDX_LOG_SIS_NIVEL   ON FAV_TB_LOG_SISTEMA (TP_NIVEL);
CREATE INDEX IDX_LOG_SIS_MODULO  ON FAV_TB_LOG_SISTEMA (NM_MODULO);
CREATE INDEX IDX_LOG_SIS_DT      ON FAV_TB_LOG_SISTEMA (DT_CRIACAO);
CREATE INDEX IDX_LOG_SIS_LOGIN   ON FAV_TB_LOG_SISTEMA (NM_LOGIN);


-- ─────────────────────────────────────────────────────────────────────────────
-- 3. LOG DE AUTENTICAÇÃO — tentativas de login (sucesso/falha)
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE FAV_TB_LOG_AUTH (
    ID_LOG        NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NM_LOGIN      VARCHAR2(50)  NOT NULL,
    TP_EVENTO     VARCHAR2(20)  NOT NULL,   -- LOGIN_OK | LOGIN_FAIL | LOGOUT | TOKEN_EXPIRE
    DS_IP_ORIGEM  VARCHAR2(50),
    DS_DETALHE    VARCHAR2(500),
    DT_EVENTO     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

COMMENT ON TABLE FAV_TB_LOG_AUTH              IS 'Histórico de autenticações (login/logout)';
COMMENT ON COLUMN FAV_TB_LOG_AUTH.TP_EVENTO   IS 'Tipo: LOGIN_OK, LOGIN_FAIL, LOGOUT, TOKEN_EXPIRE';

CREATE INDEX IDX_LOG_AUTH_LOGIN  ON FAV_TB_LOG_AUTH (NM_LOGIN);
CREATE INDEX IDX_LOG_AUTH_DT     ON FAV_TB_LOG_AUTH (DT_EVENTO);
CREATE INDEX IDX_LOG_AUTH_EVENTO ON FAV_TB_LOG_AUTH (TP_EVENTO);


-- ─────────────────────────────────────────────────────────────────────────────
-- 4. TRIGGERS DE AUDITORIA para tabelas críticas
-- ─────────────────────────────────────────────────────────────────────────────

-- 4.1 Trigger: FAV_TB_SILA_USUARIOS
CREATE OR REPLACE TRIGGER TRG_AUDIT_USUARIOS
    AFTER INSERT OR UPDATE OR DELETE
    ON FAV_TB_SILA_USUARIOS
    FOR EACH ROW
DECLARE
    v_operacao VARCHAR2(10);
    v_login    VARCHAR2(50);
    v_usuario  VARCHAR2(200);
    v_anterior CLOB;
    v_novo     CLOB;
BEGIN
    IF INSERTING THEN
        v_operacao := 'INSERT';
        v_login    := :NEW.NM_LOGIN;
        v_usuario  := :NEW.NM_USUARIO;
        v_novo     := 'login=' || :NEW.NM_LOGIN || '; perfil=' || :NEW.DS_PERFIL || '; ativo=' || :NEW.FL_ATIVO;
    ELSIF UPDATING THEN
        v_operacao := 'UPDATE';
        v_login    := :OLD.NM_LOGIN;
        v_usuario  := :OLD.NM_USUARIO;
        -- Registra campos alterados
        v_anterior := '';
        v_novo     := '';
        IF :OLD.DS_PERFIL  != :NEW.DS_PERFIL  THEN
            v_anterior := v_anterior || 'perfil='  || :OLD.DS_PERFIL  || '; ';
            v_novo     := v_novo     || 'perfil='  || :NEW.DS_PERFIL  || '; ';
        END IF;
        IF :OLD.FL_ATIVO   != :NEW.FL_ATIVO   THEN
            v_anterior := v_anterior || 'ativo='   || :OLD.FL_ATIVO   || '; ';
            v_novo     := v_novo     || 'ativo='   || :NEW.FL_ATIVO   || '; ';
        END IF;
        IF :OLD.ID_PERFIL  IS DISTINCT FROM :NEW.ID_PERFIL THEN
            v_anterior := v_anterior || 'id_perfil=' || NVL(TO_CHAR(:OLD.ID_PERFIL), 'NULL') || '; ';
            v_novo     := v_novo     || 'id_perfil=' || NVL(TO_CHAR(:NEW.ID_PERFIL), 'NULL') || '; ';
        END IF;
    ELSE
        v_operacao := 'DELETE';
        v_login    := :OLD.NM_LOGIN;
        v_usuario  := :OLD.NM_USUARIO;
        v_anterior := 'login=' || :OLD.NM_LOGIN || '; perfil=' || :OLD.DS_PERFIL;
    END IF;

    INSERT INTO FAV_TB_LOG_AUDITORIA
        (NM_TABELA, TP_OPERACAO, NM_LOGIN, NM_USUARIO,
         DT_OPERACAO, DS_DESCRICAO,
         DS_VALORES_ANTERIORES, DS_VALORES_NOVOS)
    VALUES
        ('FAV_TB_SILA_USUARIOS', v_operacao, v_login, v_usuario,
         SYSTIMESTAMP, v_operacao || ' em FAV_TB_SILA_USUARIOS',
         v_anterior, v_novo);
EXCEPTION
    WHEN OTHERS THEN NULL;  -- Não deixa o trigger quebrar a operação principal
END TRG_AUDIT_USUARIOS;
/


-- 4.2 Trigger: FAV_TB_PERFIS
CREATE OR REPLACE TRIGGER TRG_AUDIT_PERFIS
    AFTER INSERT OR UPDATE OR DELETE
    ON FAV_TB_PERFIS
    FOR EACH ROW
DECLARE
    v_operacao VARCHAR2(10);
    v_detalhe  VARCHAR2(500);
BEGIN
    IF INSERTING    THEN v_operacao := 'INSERT'; v_detalhe := 'ds_perfil=' || :NEW.DS_PERFIL;
    ELSIF UPDATING  THEN v_operacao := 'UPDATE'; v_detalhe := 'de=' || :OLD.DS_PERFIL || ' para=' || :NEW.DS_PERFIL;
    ELSE                 v_operacao := 'DELETE'; v_detalhe := 'ds_perfil=' || :OLD.DS_PERFIL;
    END IF;

    INSERT INTO FAV_TB_LOG_AUDITORIA
        (NM_TABELA, TP_OPERACAO, DT_OPERACAO, DS_DESCRICAO, DS_VALORES_NOVOS)
    VALUES
        ('FAV_TB_PERFIS', v_operacao, SYSTIMESTAMP,
         v_operacao || ' em FAV_TB_PERFIS', v_detalhe);
EXCEPTION
    WHEN OTHERS THEN NULL;
END TRG_AUDIT_PERFIS;
/


-- 4.3 Trigger: FAV_TB_PTS (só UPDATE — acompanha mudanças de status)
CREATE OR REPLACE TRIGGER TRG_AUDIT_PTS
    AFTER INSERT OR UPDATE OR DELETE
    ON FAV_TB_PTS
    FOR EACH ROW
DECLARE
    v_operacao VARCHAR2(10);
    v_anterior CLOB;
    v_novo     CLOB;
BEGIN
    IF INSERTING THEN
        v_operacao := 'INSERT';
        v_novo     := 'id_paciente=' || :NEW.ID_PACIENTE || '; status=' || :NEW.DS_STATUS;
    ELSIF UPDATING THEN
        v_operacao := 'UPDATE';
        v_anterior := 'status=' || :OLD.DS_STATUS;
        v_novo     := 'status=' || :NEW.DS_STATUS;
    ELSE
        v_operacao := 'DELETE';
        v_anterior := 'id_pts=' || :OLD.ID_PTS || '; status=' || :OLD.DS_STATUS;
    END IF;

    INSERT INTO FAV_TB_LOG_AUDITORIA
        (NM_TABELA, TP_OPERACAO, DT_OPERACAO, DS_DESCRICAO,
         DS_VALORES_ANTERIORES, DS_VALORES_NOVOS)
    VALUES
        ('FAV_TB_PTS', v_operacao, SYSTIMESTAMP,
         v_operacao || ' em FAV_TB_PTS',
         v_anterior, v_novo);
EXCEPTION
    WHEN OTHERS THEN NULL;
END TRG_AUDIT_PTS;
/


-- ─────────────────────────────────────────────────────────────────────────────
-- 5. VIEW auxiliar para consultas de auditoria com joins
-- ─────────────────────────────────────────────────────────────────────────────

CREATE OR REPLACE VIEW FAV_VW_AUDIT_COMPLETO AS
SELECT
    a.ID_LOG,
    a.NM_TABELA,
    a.TP_OPERACAO,
    a.NM_LOGIN,
    a.NM_USUARIO,
    a.DT_OPERACAO,
    a.DS_DESCRICAO,
    a.DS_VALORES_ANTERIORES,
    a.DS_VALORES_NOVOS,
    u.ID_USUARIO,
    p.DS_PERFIL  AS DS_PERFIL_ATUAL
FROM FAV_TB_LOG_AUDITORIA a
LEFT JOIN FAV_TB_SILA_USUARIOS u ON LOWER(a.NM_LOGIN) = LOWER(u.NM_LOGIN)
LEFT JOIN FAV_TB_PERFIS        p ON u.ID_PERFIL = p.ID_PERFIL;

COMMENT ON VIEW FAV_VW_AUDIT_COMPLETO IS 'Log de auditoria enriquecido com dados do usuário';


COMMIT;
